builds:
  - binary: pbm-agent
    main: cli/pbm-agent/main.go
    goarch:
      - amd64
    ldflags:
      - "-w -s -X main.version={{ .Version }} -X main.commit={{ .Commit }}"
    env:
      - CGO_ENABLED=0
    hooks:
      post: "./post-build.sh pbm-agent"
  - binary: pbm-coordinator
    main: ./cli/pbm-coordinator/main.go
    goarch:
      - amd64
    ldflags:
      - "-w -s -X main.version={{ .Version }} -X main.commit={{ .Commit }}"
    env:
      - CGO_ENABLED=0
    hooks:
      post: "./post-build.sh pbm-coordinator"
  - binary: pbmctl
    main: ./cli/pbmctl/main.go
    goarch:
      - amd64
    ldflags:
      - "-w -s -X main.version={{ .Version }} -X main.commit={{ .Commit }}"
    env:
      - CGO_ENABLED=0
    hooks:
      post: "./post-build.sh pbmctl"
#dockers:
#  - binary: pbm-agent
#    dockerfile: docker/agent/Dockerfile
#    image_templates:
#      - "percona/percona-backup-mongodb:agent"
#      - "percona/percona-backup-mongodb:{{ .Tag }}-agent"
#    skip_push: true
#  - binary: pbm-coordinator
#    dockerfile: docker/coordinator/Dockerfile
#    image_templates:
#      - "percona/percona-backup-mongodb:coordinator"
#      - "percona/percona-backup-mongodb:{{ .Tag }}-coordinator"
#    skip_push: true
#  - binary: pbmctl
#    dockerfile: docker/pbmctl/Dockerfile
#    image_templates:
#      - "percona/percona-backup-mongodb:pbmctl"
#      - "percona/percona-backup-mongodb:{{ .Tag }}-pbmctl"
#    skip_push: true
archive:
  replacements:
    amd64: x86_64
nfpm:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  vendor: Percona LLC.
  homepage: https://github.com/percona/percona-backup-mongodb
  maintainer: Percona <percona-backup-mongodb@percona.com>
  description: Percona Backup for MongoDB
  license: Apache 2.0
  formats:
    - deb
    - rpm
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .ShortCommit }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '_test.go'
      - 'README.md'
