builds:
  - binary: pbm-agent
    main: cli/pbm-agent/main.go
    ldflags:
      - -w -s
    env:
      - CGO_ENABLED=0
    hooks:
      post: "./post-build.sh pbm-agent"
  - binary: pbm-coordinator
    main: ./cli/pbm-coordinator/main.go
    ldflags:
      - -w -s
    env:
      - CGO_ENABLED=0
    hooks:
      post: "./post-build.sh pbm-coordinator"
  - binary: pbmctl
    main: ./cli/pbmctl/main.go
    ldflags:
      - -w -s
    env:
      - CGO_ENABLED=0
    hooks:
      post: "./post-build.sh pbmctl"
dockers:
  - binary: pbm-agent
    dockerfile: docker/agent/Dockerfile
    image_templates:
      - "percona/mongodb-backup:agent"
      - "percona/mongodb-backup:{{ .Tag }}-agent"
      - "percona/mongodb-backup:v{{ .Major }}.{{ .Minor }}-agent"
    skip_push: true
  - binary: pbm-coordinator
    dockerfile: docker/coordinator/Dockerfile
    image_templates:
      - "percona/mongodb-backup:coordinator"
      - "percona/mongodb-backup:{{ .Tag }}-coordinator"
      - "percona/mongodb-backup:v{{ .Major }}.{{ .Minor }}-coordinator"
    skip_push: true
archive:
  replacements:
    386: i386
    amd64: x86_64
nfpm:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  vendor: Percona LLC.
  homepage: https://www.percona.com/software
  maintainer: Percona <mongodb-backup@percona.com>
  description: MongoDB Backup tool
  license: Apache 2.0
  formats:
    - deb
    - rpm
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .ShortCommit }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '_test.go'
      - 'README.md'
