ARG GOLANG_DOCKERHUB_TAG
FROM golang:$GOLANG_DOCKERHUB_TAG

WORKDIR /go/src/github.com/percona/mongodb-backup
COPY . .

RUN go get ./...

CMD GOCACHE=off go test -race -coverprofile=/tmp/out/cover.out -covermode=atomic -v ./...
