ARG GOLANG_DOCKERHUB_TAG
FROM golang:$GOLANG_DOCKERHUB_TAG

WORKDIR /go/src/github.com/percona/mongodb-backup
COPY . .

RUN go get -v ./...

USER nobody
CMD GOCACHE=off go test -race -coverprofile=/tmp/cover.out -covermode=atomic -v ./...
