#!/bin/bash

# source $(readlink -f $(dirname $0))/.env

export DEBUG=1
export AWS_ACCESS_KEY_ID=
export AWS_SECRET_ACCESS_KEY=
export GOCACHE=off
export GOLANG_DOCKERHUB_TAG=1.10-stretch
export TEST_MONGODB_ADMIN_USERNAME=admin
export TEST_MONGODB_ADMIN_PASSWORD=admin123456
export TEST_MONGODB_USERNAME=test
export TEST_MONGODB_PASSWORD=123456
export TEST_MONGODB_RS=rs
export TEST_MONGODB_CONFIGSVR_RS=csReplSet
export TEST_MONGODB_PRIMARY_PORT=17001
export TEST_MONGODB_SECONDARY1_PORT=17002
export TEST_MONGODB_SECONDARY2_PORT=17003
export TEST_MONGODB_CONFIGSVR1_PORT=17004
export TEST_MONGODB_MONGOS_PORT=17000
export TEST_PSMDB_VERSION=latest
