#!/bin/sh
SOURCE_DIR=$1
BUILD_ROOT=$2
cd $SOURCE_DIR

install -m 0755 -d $BUILD_ROOT/usr/bin
install -m 0755 bin/pmbctl $BUILD_ROOT/usr/bin/
install -m 0755 bin/pmb-agent $BUILD_ROOT/usr/bin/
install -m 0755 bin/pmb-coordinator $BUILD_ROOT/usr/bin/
