// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages/messages.proto

package messages

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ErrorType int32

const (
	ErrorType_NO_ERROR                  ErrorType = 0
	ErrorType_NOT_IMPLEMENTED_YET       ErrorType = 1
	ErrorType_COMMUNICATION_ERROR       ErrorType = 2
	ErrorType_CLIENT_ALREADY_REGISTERED ErrorType = 3
)

var ErrorType_name = map[int32]string{
	0: "NO_ERROR",
	1: "NOT_IMPLEMENTED_YET",
	2: "COMMUNICATION_ERROR",
	3: "CLIENT_ALREADY_REGISTERED",
}

var ErrorType_value = map[string]int32{
	"NO_ERROR":                  0,
	"NOT_IMPLEMENTED_YET":       1,
	"COMMUNICATION_ERROR":       2,
	"CLIENT_ALREADY_REGISTERED": 3,
}

func (x ErrorType) String() string {
	return proto.EnumName(ErrorType_name, int32(x))
}

func (ErrorType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_83994550f81e9f35, []int{0}
}

type BackupType int32

const (
	BackupType_LOGICAL   BackupType = 0
	BackupType_HOTBACKUP BackupType = 1
)

var BackupType_name = map[int32]string{
	0: "LOGICAL",
	1: "HOTBACKUP",
}

var BackupType_value = map[string]int32{
	"LOGICAL":   0,
	"HOTBACKUP": 1,
}

func (x BackupType) String() string {
	return proto.EnumName(BackupType_name, int32(x))
}

func (BackupType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_83994550f81e9f35, []int{1}
}

type DestinationType int32

const (
	DestinationType_FILE DestinationType = 0
	DestinationType_AWS  DestinationType = 1
)

var DestinationType_name = map[int32]string{
	0: "FILE",
	1: "AWS",
}

var DestinationType_value = map[string]int32{
	"FILE": 0,
	"AWS":  1,
}

func (x DestinationType) String() string {
	return proto.EnumName(DestinationType_name, int32(x))
}

func (DestinationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_83994550f81e9f35, []int{2}
}

type CompressionType int32

const (
	CompressionType_NO_COMPRESSION CompressionType = 0
	CompressionType_GZIP           CompressionType = 1
	CompressionType_SNAPPY         CompressionType = 2
	CompressionType_LZ4            CompressionType = 3
)

var CompressionType_name = map[int32]string{
	0: "NO_COMPRESSION",
	1: "GZIP",
	2: "SNAPPY",
	3: "LZ4",
}

var CompressionType_value = map[string]int32{
	"NO_COMPRESSION": 0,
	"GZIP":           1,
	"SNAPPY":         2,
	"LZ4":            3,
}

func (x CompressionType) String() string {
	return proto.EnumName(CompressionType_name, int32(x))
}

func (CompressionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_83994550f81e9f35, []int{3}
}

type Cypher int32

const (
	Cypher_NO_CYPHER Cypher = 0
	Cypher_AES       Cypher = 1
	Cypher_DES       Cypher = 2
	Cypher_RC4       Cypher = 3
	Cypher_RSA       Cypher = 4
)

var Cypher_name = map[int32]string{
	0: "NO_CYPHER",
	1: "AES",
	2: "DES",
	3: "RC4",
	4: "RSA",
}

var Cypher_value = map[string]int32{
	"NO_CYPHER": 0,
	"AES":       1,
	"DES":       2,
	"RC4":       3,
	"RSA":       4,
}

func (x Cypher) String() string {
	return proto.EnumName(Cypher_name, int32(x))
}

func (Cypher) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_83994550f81e9f35, []int{4}
}

type NodeType int32

const (
	NodeType_UNDEFINED        NodeType = 0
	NodeType_MONGOD           NodeType = 1
	NodeType_MONGOD_REPLSET   NodeType = 2
	NodeType_MONGOD_SHARDSVR  NodeType = 3
	NodeType_MONGOD_CONFIGSVR NodeType = 4
	NodeType_MONGOS           NodeType = 5
)

var NodeType_name = map[int32]string{
	0: "UNDEFINED",
	1: "MONGOD",
	2: "MONGOD_REPLSET",
	3: "MONGOD_SHARDSVR",
	4: "MONGOD_CONFIGSVR",
	5: "MONGOS",
}

var NodeType_value = map[string]int32{
	"UNDEFINED":        0,
	"MONGOD":           1,
	"MONGOD_REPLSET":   2,
	"MONGOD_SHARDSVR":  3,
	"MONGOD_CONFIGSVR": 4,
	"MONGOS":           5,
}

func (x NodeType) String() string {
	return proto.EnumName(NodeType_name, int32(x))
}

func (NodeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_83994550f81e9f35, []int{5}
}

type RestoreStatus int32

const (
	RestoreStatus_Not_Running    RestoreStatus = 0
	RestoreStatus_RestoringDB    RestoreStatus = 1
	RestoreStatus_RestoringOplog RestoreStatus = 2
)

var RestoreStatus_name = map[int32]string{
	0: "Not_Running",
	1: "RestoringDB",
	2: "RestoringOplog",
}

var RestoreStatus_value = map[string]int32{
	"Not_Running":    0,
	"RestoringDB":    1,
	"RestoringOplog": 2,
}

func (x RestoreStatus) String() string {
	return proto.EnumName(RestoreStatus_name, int32(x))
}

func (RestoreStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_83994550f81e9f35, []int{6}
}

type Ack struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ack) Reset()         { *m = Ack{} }
func (m *Ack) String() string { return proto.CompactTextString(m) }
func (*Ack) ProtoMessage()    {}
func (*Ack) Descriptor() ([]byte, []int) {
	return fileDescriptor_83994550f81e9f35, []int{0}
}

func (m *Ack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ack.Unmarshal(m, b)
}
func (m *Ack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ack.Marshal(b, m, deterministic)
}
func (m *Ack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ack.Merge(m, src)
}
func (m *Ack) XXX_Size() int {
	return xxx_messageInfo_Ack.Size(m)
}
func (m *Ack) XXX_DiscardUnknown() {
	xxx_messageInfo_Ack.DiscardUnknown(m)
}

var xxx_messageInfo_Ack proto.InternalMessageInfo

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_83994550f81e9f35, []int{1}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type GetBackupSource struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBackupSource) Reset()         { *m = GetBackupSource{} }
func (m *GetBackupSource) String() string { return proto.CompactTextString(m) }
func (*GetBackupSource) ProtoMessage()    {}
func (*GetBackupSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_83994550f81e9f35, []int{2}
}

func (m *GetBackupSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBackupSource.Unmarshal(m, b)
}
func (m *GetBackupSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBackupSource.Marshal(b, m, deterministic)
}
func (m *GetBackupSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBackupSource.Merge(m, src)
}
func (m *GetBackupSource) XXX_Size() int {
	return xxx_messageInfo_GetBackupSource.Size(m)
}
func (m *GetBackupSource) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBackupSource.DiscardUnknown(m)
}

var xxx_messageInfo_GetBackupSource proto.InternalMessageInfo

type CancelBackup struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelBackup) Reset()         { *m = CancelBackup{} }
func (m *CancelBackup) String() string { return proto.CompactTextString(m) }
func (*CancelBackup) ProtoMessage()    {}
func (*CancelBackup) Descriptor() ([]byte, []int) {
	return fileDescriptor_83994550f81e9f35, []int{3}
}

func (m *CancelBackup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelBackup.Unmarshal(m, b)
}
func (m *CancelBackup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelBackup.Marshal(b, m, deterministic)
}
func (m *CancelBackup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelBackup.Merge(m, src)
}
func (m *CancelBackup) XXX_Size() int {
	return xxx_messageInfo_CancelBackup.Size(m)
}
func (m *CancelBackup) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelBackup.DiscardUnknown(m)
}

var xxx_messageInfo_CancelBackup proto.InternalMessageInfo

type GetStatus struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStatus) Reset()         { *m = GetStatus{} }
func (m *GetStatus) String() string { return proto.CompactTextString(m) }
func (*GetStatus) ProtoMessage()    {}
func (*GetStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_83994550f81e9f35, []int{4}
}

func (m *GetStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatus.Unmarshal(m, b)
}
func (m *GetStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatus.Marshal(b, m, deterministic)
}
func (m *GetStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatus.Merge(m, src)
}
func (m *GetStatus) XXX_Size() int {
	return xxx_messageInfo_GetStatus.Size(m)
}
func (m *GetStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatus.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatus proto.InternalMessageInfo

type Ping struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_83994550f81e9f35, []int{5}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

type StartBalancer struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartBalancer) Reset()         { *m = StartBalancer{} }
func (m *StartBalancer) String() string { return proto.CompactTextString(m) }
func (*StartBalancer) ProtoMessage()    {}
func (*StartBalancer) Descriptor() ([]byte, []int) {
	return fileDescriptor_83994550f81e9f35, []int{6}
}

func (m *StartBalancer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartBalancer.Unmarshal(m, b)
}
func (m *StartBalancer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartBalancer.Marshal(b, m, deterministic)
}
func (m *StartBalancer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartBalancer.Merge(m, src)
}
func (m *StartBalancer) XXX_Size() int {
	return xxx_messageInfo_StartBalancer.Size(m)
}
func (m *StartBalancer) XXX_DiscardUnknown() {
	xxx_messageInfo_StartBalancer.DiscardUnknown(m)
}

var xxx_messageInfo_StartBalancer proto.InternalMessageInfo

type StopBalancer struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopBalancer) Reset()         { *m = StopBalancer{} }
func (m *StopBalancer) String() string { return proto.CompactTextString(m) }
func (*StopBalancer) ProtoMessage()    {}
func (*StopBalancer) Descriptor() ([]byte, []int) {
	return fileDescriptor_83994550f81e9f35, []int{7}
}

func (m *StopBalancer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopBalancer.Unmarshal(m, b)
}
func (m *StopBalancer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopBalancer.Marshal(b, m, deterministic)
}
func (m *StopBalancer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopBalancer.Merge(m, src)
}
func (m *StopBalancer) XXX_Size() int {
	return xxx_messageInfo_StopBalancer.Size(m)
}
func (m *StopBalancer) XXX_DiscardUnknown() {
	xxx_messageInfo_StopBalancer.DiscardUnknown(m)
}

var xxx_messageInfo_StopBalancer proto.InternalMessageInfo

type ReplicasetMetadata struct {
	ReplicasetUUID       string   `protobuf:"bytes,1,opt,name=ReplicasetUUID,proto3" json:"ReplicasetUUID,omitempty"`
	ReplicasetName       string   `protobuf:"bytes,2,opt,name=ReplicasetName,proto3" json:"ReplicasetName,omitempty"`
	DBBackupName         string   `protobuf:"bytes,3,opt,name=DBBackupName,proto3" json:"DBBackupName,omitempty"`
	OplogBackupName      string   `protobuf:"bytes,4,opt,name=OplogBackupName,proto3" json:"OplogBackupName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplicasetMetadata) Reset()         { *m = ReplicasetMetadata{} }
func (m *ReplicasetMetadata) String() string { return proto.CompactTextString(m) }
func (*ReplicasetMetadata) ProtoMessage()    {}
func (*ReplicasetMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_83994550f81e9f35, []int{8}
}

func (m *ReplicasetMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicasetMetadata.Unmarshal(m, b)
}
func (m *ReplicasetMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicasetMetadata.Marshal(b, m, deterministic)
}
func (m *ReplicasetMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicasetMetadata.Merge(m, src)
}
func (m *ReplicasetMetadata) XXX_Size() int {
	return xxx_messageInfo_ReplicasetMetadata.Size(m)
}
func (m *ReplicasetMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicasetMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicasetMetadata proto.InternalMessageInfo

func (m *ReplicasetMetadata) GetReplicasetUUID() string {
	if m != nil {
		return m.ReplicasetUUID
	}
	return ""
}

func (m *ReplicasetMetadata) GetReplicasetName() string {
	if m != nil {
		return m.ReplicasetName
	}
	return ""
}

func (m *ReplicasetMetadata) GetDBBackupName() string {
	if m != nil {
		return m.DBBackupName
	}
	return ""
}

func (m *ReplicasetMetadata) GetOplogBackupName() string {
	if m != nil {
		return m.OplogBackupName
	}
	return ""
}

type BackupMetadata struct {
	StartTs              int64                          `protobuf:"varint,1,opt,name=StartTs,proto3" json:"StartTs,omitempty"`
	EndTs                int64                          `protobuf:"varint,2,opt,name=EndTs,proto3" json:"EndTs,omitempty"`
	BackupType           BackupType                     `protobuf:"varint,3,opt,name=BackupType,proto3,enum=messages.BackupType" json:"BackupType,omitempty"`
	OplogStartTime       int64                          `protobuf:"varint,4,opt,name=OplogStartTime,proto3" json:"OplogStartTime,omitempty"`
	LastOplogTs          int64                          `protobuf:"varint,5,opt,name=LastOplogTs,proto3" json:"LastOplogTs,omitempty"`
	DestinationType      DestinationType                `protobuf:"varint,6,opt,name=DestinationType,proto3,enum=messages.DestinationType" json:"DestinationType,omitempty"`
	DestinationDir       string                         `protobuf:"bytes,7,opt,name=DestinationDir,proto3" json:"DestinationDir,omitempty"`
	Cypher               Cypher                         `protobuf:"varint,8,opt,name=Cypher,proto3,enum=messages.Cypher" json:"Cypher,omitempty"`
	CompressionType      CompressionType                `protobuf:"varint,9,opt,name=CompressionType,proto3,enum=messages.CompressionType" json:"CompressionType,omitempty"`
	Description          string                         `protobuf:"bytes,10,opt,name=Description,proto3" json:"Description,omitempty"`
	Replicasets          map[string]*ReplicasetMetadata `protobuf:"bytes,11,rep,name=Replicasets,proto3" json:"Replicasets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *BackupMetadata) Reset()         { *m = BackupMetadata{} }
func (m *BackupMetadata) String() string { return proto.CompactTextString(m) }
func (*BackupMetadata) ProtoMessage()    {}
func (*BackupMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_83994550f81e9f35, []int{9}
}

func (m *BackupMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupMetadata.Unmarshal(m, b)
}
func (m *BackupMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupMetadata.Marshal(b, m, deterministic)
}
func (m *BackupMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupMetadata.Merge(m, src)
}
func (m *BackupMetadata) XXX_Size() int {
	return xxx_messageInfo_BackupMetadata.Size(m)
}
func (m *BackupMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_BackupMetadata proto.InternalMessageInfo

func (m *BackupMetadata) GetStartTs() int64 {
	if m != nil {
		return m.StartTs
	}
	return 0
}

func (m *BackupMetadata) GetEndTs() int64 {
	if m != nil {
		return m.EndTs
	}
	return 0
}

func (m *BackupMetadata) GetBackupType() BackupType {
	if m != nil {
		return m.BackupType
	}
	return BackupType_LOGICAL
}

func (m *BackupMetadata) GetOplogStartTime() int64 {
	if m != nil {
		return m.OplogStartTime
	}
	return 0
}

func (m *BackupMetadata) GetLastOplogTs() int64 {
	if m != nil {
		return m.LastOplogTs
	}
	return 0
}

func (m *BackupMetadata) GetDestinationType() DestinationType {
	if m != nil {
		return m.DestinationType
	}
	return DestinationType_FILE
}

func (m *BackupMetadata) GetDestinationDir() string {
	if m != nil {
		return m.DestinationDir
	}
	return ""
}

func (m *BackupMetadata) GetCypher() Cypher {
	if m != nil {
		return m.Cypher
	}
	return Cypher_NO_CYPHER
}

func (m *BackupMetadata) GetCompressionType() CompressionType {
	if m != nil {
		return m.CompressionType
	}
	return CompressionType_NO_COMPRESSION
}

func (m *BackupMetadata) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *BackupMetadata) GetReplicasets() map[string]*ReplicasetMetadata {
	if m != nil {
		return m.Replicasets
	}
	return nil
}

type LogEntry struct {
	ClientID             string   `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	Level                uint32   `protobuf:"varint,2,opt,name=Level,proto3" json:"Level,omitempty"`
	Ts                   int64    `protobuf:"varint,3,opt,name=Ts,proto3" json:"Ts,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogEntry) Reset()         { *m = LogEntry{} }
func (m *LogEntry) String() string { return proto.CompactTextString(m) }
func (*LogEntry) ProtoMessage()    {}
func (*LogEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_83994550f81e9f35, []int{10}
}

func (m *LogEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogEntry.Unmarshal(m, b)
}
func (m *LogEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogEntry.Marshal(b, m, deterministic)
}
func (m *LogEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogEntry.Merge(m, src)
}
func (m *LogEntry) XXX_Size() int {
	return xxx_messageInfo_LogEntry.Size(m)
}
func (m *LogEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_LogEntry.DiscardUnknown(m)
}

var xxx_messageInfo_LogEntry proto.InternalMessageInfo

func (m *LogEntry) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *LogEntry) GetLevel() uint32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *LogEntry) GetTs() int64 {
	if m != nil {
		return m.Ts
	}
	return 0
}

func (m *LogEntry) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RestoreBackup struct {
	BackupType           BackupType      `protobuf:"varint,1,opt,name=BackupType,proto3,enum=messages.BackupType" json:"BackupType,omitempty"`
	SourceType           DestinationType `protobuf:"varint,2,opt,name=SourceType,proto3,enum=messages.DestinationType" json:"SourceType,omitempty"`
	SourceBucket         string          `protobuf:"bytes,3,opt,name=SourceBucket,proto3" json:"SourceBucket,omitempty"`
	DBSourceName         string          `protobuf:"bytes,4,opt,name=DBSourceName,proto3" json:"DBSourceName,omitempty"`
	OplogSourceName      string          `protobuf:"bytes,5,opt,name=OplogSourceName,proto3" json:"OplogSourceName,omitempty"`
	CompressionType      CompressionType `protobuf:"varint,6,opt,name=CompressionType,proto3,enum=messages.CompressionType" json:"CompressionType,omitempty"`
	Cypher               Cypher          `protobuf:"varint,7,opt,name=Cypher,proto3,enum=messages.Cypher" json:"Cypher,omitempty"`
	OplogStartTime       int64           `protobuf:"varint,8,opt,name=OplogStartTime,proto3" json:"OplogStartTime,omitempty"`
	SkipUsersAndRoles    bool            `protobuf:"varint,9,opt,name=SkipUsersAndRoles,proto3" json:"SkipUsersAndRoles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RestoreBackup) Reset()         { *m = RestoreBackup{} }
func (m *RestoreBackup) String() string { return proto.CompactTextString(m) }
func (*RestoreBackup) ProtoMessage()    {}
func (*RestoreBackup) Descriptor() ([]byte, []int) {
	return fileDescriptor_83994550f81e9f35, []int{11}
}

func (m *RestoreBackup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestoreBackup.Unmarshal(m, b)
}
func (m *RestoreBackup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestoreBackup.Marshal(b, m, deterministic)
}
func (m *RestoreBackup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestoreBackup.Merge(m, src)
}
func (m *RestoreBackup) XXX_Size() int {
	return xxx_messageInfo_RestoreBackup.Size(m)
}
func (m *RestoreBackup) XXX_DiscardUnknown() {
	xxx_messageInfo_RestoreBackup.DiscardUnknown(m)
}

var xxx_messageInfo_RestoreBackup proto.InternalMessageInfo

func (m *RestoreBackup) GetBackupType() BackupType {
	if m != nil {
		return m.BackupType
	}
	return BackupType_LOGICAL
}

func (m *RestoreBackup) GetSourceType() DestinationType {
	if m != nil {
		return m.SourceType
	}
	return DestinationType_FILE
}

func (m *RestoreBackup) GetSourceBucket() string {
	if m != nil {
		return m.SourceBucket
	}
	return ""
}

func (m *RestoreBackup) GetDBSourceName() string {
	if m != nil {
		return m.DBSourceName
	}
	return ""
}

func (m *RestoreBackup) GetOplogSourceName() string {
	if m != nil {
		return m.OplogSourceName
	}
	return ""
}

func (m *RestoreBackup) GetCompressionType() CompressionType {
	if m != nil {
		return m.CompressionType
	}
	return CompressionType_NO_COMPRESSION
}

func (m *RestoreBackup) GetCypher() Cypher {
	if m != nil {
		return m.Cypher
	}
	return Cypher_NO_CYPHER
}

func (m *RestoreBackup) GetOplogStartTime() int64 {
	if m != nil {
		return m.OplogStartTime
	}
	return 0
}

func (m *RestoreBackup) GetSkipUsersAndRoles() bool {
	if m != nil {
		return m.SkipUsersAndRoles
	}
	return false
}

type RestoreComplete struct {
	ClientID             string   `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	Err                  *Error   `protobuf:"bytes,2,opt,name=Err,proto3" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestoreComplete) Reset()         { *m = RestoreComplete{} }
func (m *RestoreComplete) String() string { return proto.CompactTextString(m) }
func (*RestoreComplete) ProtoMessage()    {}
func (*RestoreComplete) Descriptor() ([]byte, []int) {
	return fileDescriptor_83994550f81e9f35, []int{12}
}

func (m *RestoreComplete) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestoreComplete.Unmarshal(m, b)
}
func (m *RestoreComplete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestoreComplete.Marshal(b, m, deterministic)
}
func (m *RestoreComplete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestoreComplete.Merge(m, src)
}
func (m *RestoreComplete) XXX_Size() int {
	return xxx_messageInfo_RestoreComplete.Size(m)
}
func (m *RestoreComplete) XXX_DiscardUnknown() {
	xxx_messageInfo_RestoreComplete.DiscardUnknown(m)
}

var xxx_messageInfo_RestoreComplete proto.InternalMessageInfo

func (m *RestoreComplete) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *RestoreComplete) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type Error struct {
	Message              string    `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	Code                 ErrorType `protobuf:"varint,2,opt,name=Code,proto3,enum=messages.ErrorType" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_83994550f81e9f35, []int{13}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetCode() ErrorType {
	if m != nil {
		return m.Code
	}
	return ErrorType_NO_ERROR
}

type StartBackup struct {
	BackupType           BackupType      `protobuf:"varint,1,opt,name=BackupType,proto3,enum=messages.BackupType" json:"BackupType,omitempty"`
	DestinationType      DestinationType `protobuf:"varint,2,opt,name=DestinationType,proto3,enum=messages.DestinationType" json:"DestinationType,omitempty"`
	NamePrefix           string          `protobuf:"bytes,3,opt,name=NamePrefix,proto3" json:"NamePrefix,omitempty"`
	DBBackupName         string          `protobuf:"bytes,4,opt,name=DBBackupName,proto3" json:"DBBackupName,omitempty"`
	OplogBackupName      string          `protobuf:"bytes,5,opt,name=OplogBackupName,proto3" json:"OplogBackupName,omitempty"`
	DestinationDir       string          `protobuf:"bytes,6,opt,name=DestinationDir,proto3" json:"DestinationDir,omitempty"`
	CompressionType      CompressionType `protobuf:"varint,7,opt,name=CompressionType,proto3,enum=messages.CompressionType" json:"CompressionType,omitempty"`
	Cypher               Cypher          `protobuf:"varint,8,opt,name=Cypher,proto3,enum=messages.Cypher" json:"Cypher,omitempty"`
	OplogStartTime       int64           `protobuf:"varint,9,opt,name=OplogStartTime,proto3" json:"OplogStartTime,omitempty"`
	Description          string          `protobuf:"bytes,10,opt,name=Description,proto3" json:"Description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *StartBackup) Reset()         { *m = StartBackup{} }
func (m *StartBackup) String() string { return proto.CompactTextString(m) }
func (*StartBackup) ProtoMessage()    {}
func (*StartBackup) Descriptor() ([]byte, []int) {
	return fileDescriptor_83994550f81e9f35, []int{14}
}

func (m *StartBackup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartBackup.Unmarshal(m, b)
}
func (m *StartBackup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartBackup.Marshal(b, m, deterministic)
}
func (m *StartBackup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartBackup.Merge(m, src)
}
func (m *StartBackup) XXX_Size() int {
	return xxx_messageInfo_StartBackup.Size(m)
}
func (m *StartBackup) XXX_DiscardUnknown() {
	xxx_messageInfo_StartBackup.DiscardUnknown(m)
}

var xxx_messageInfo_StartBackup proto.InternalMessageInfo

func (m *StartBackup) GetBackupType() BackupType {
	if m != nil {
		return m.BackupType
	}
	return BackupType_LOGICAL
}

func (m *StartBackup) GetDestinationType() DestinationType {
	if m != nil {
		return m.DestinationType
	}
	return DestinationType_FILE
}

func (m *StartBackup) GetNamePrefix() string {
	if m != nil {
		return m.NamePrefix
	}
	return ""
}

func (m *StartBackup) GetDBBackupName() string {
	if m != nil {
		return m.DBBackupName
	}
	return ""
}

func (m *StartBackup) GetOplogBackupName() string {
	if m != nil {
		return m.OplogBackupName
	}
	return ""
}

func (m *StartBackup) GetDestinationDir() string {
	if m != nil {
		return m.DestinationDir
	}
	return ""
}

func (m *StartBackup) GetCompressionType() CompressionType {
	if m != nil {
		return m.CompressionType
	}
	return CompressionType_NO_COMPRESSION
}

func (m *StartBackup) GetCypher() Cypher {
	if m != nil {
		return m.Cypher
	}
	return Cypher_NO_CYPHER
}

func (m *StartBackup) GetOplogStartTime() int64 {
	if m != nil {
		return m.OplogStartTime
	}
	return 0
}

func (m *StartBackup) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type StopOplogTail struct {
	Ts                   int64    `protobuf:"varint,1,opt,name=Ts,proto3" json:"Ts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopOplogTail) Reset()         { *m = StopOplogTail{} }
func (m *StopOplogTail) String() string { return proto.CompactTextString(m) }
func (*StopOplogTail) ProtoMessage()    {}
func (*StopOplogTail) Descriptor() ([]byte, []int) {
	return fileDescriptor_83994550f81e9f35, []int{15}
}

func (m *StopOplogTail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopOplogTail.Unmarshal(m, b)
}
func (m *StopOplogTail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopOplogTail.Marshal(b, m, deterministic)
}
func (m *StopOplogTail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopOplogTail.Merge(m, src)
}
func (m *StopOplogTail) XXX_Size() int {
	return xxx_messageInfo_StopOplogTail.Size(m)
}
func (m *StopOplogTail) XXX_DiscardUnknown() {
	xxx_messageInfo_StopOplogTail.DiscardUnknown(m)
}

var xxx_messageInfo_StopOplogTail proto.InternalMessageInfo

func (m *StopOplogTail) GetTs() int64 {
	if m != nil {
		return m.Ts
	}
	return 0
}

type ServerMessage struct {
	Version int32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Types that are valid to be assigned to Payload:
	//	*ServerMessage_AckMsg
	//	*ServerMessage_BackupSourceMsg
	//	*ServerMessage_GetStatusMsg
	//	*ServerMessage_PingMsg
	//	*ServerMessage_ErrorMsg
	//	*ServerMessage_StartBalancerMsg
	//	*ServerMessage_StopBalancerMsg
	//	*ServerMessage_StartBackupMsg
	//	*ServerMessage_CancelBackupMsg
	//	*ServerMessage_StopOplogTailMsg
	//	*ServerMessage_RestoreBackupMsg
	Payload              isServerMessage_Payload `protobuf_oneof:"Payload"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ServerMessage) Reset()         { *m = ServerMessage{} }
func (m *ServerMessage) String() string { return proto.CompactTextString(m) }
func (*ServerMessage) ProtoMessage()    {}
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_83994550f81e9f35, []int{16}
}

func (m *ServerMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerMessage.Unmarshal(m, b)
}
func (m *ServerMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerMessage.Marshal(b, m, deterministic)
}
func (m *ServerMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerMessage.Merge(m, src)
}
func (m *ServerMessage) XXX_Size() int {
	return xxx_messageInfo_ServerMessage.Size(m)
}
func (m *ServerMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ServerMessage proto.InternalMessageInfo

func (m *ServerMessage) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_AckMsg struct {
	AckMsg *Ack `protobuf:"bytes,2,opt,name=AckMsg,proto3,oneof"`
}

type ServerMessage_BackupSourceMsg struct {
	BackupSourceMsg *GetBackupSource `protobuf:"bytes,3,opt,name=BackupSourceMsg,proto3,oneof"`
}

type ServerMessage_GetStatusMsg struct {
	GetStatusMsg *GetStatus `protobuf:"bytes,4,opt,name=GetStatusMsg,proto3,oneof"`
}

type ServerMessage_PingMsg struct {
	PingMsg *Ping `protobuf:"bytes,5,opt,name=PingMsg,proto3,oneof"`
}

type ServerMessage_ErrorMsg struct {
	ErrorMsg *Error `protobuf:"bytes,6,opt,name=ErrorMsg,proto3,oneof"`
}

type ServerMessage_StartBalancerMsg struct {
	StartBalancerMsg *StartBalancer `protobuf:"bytes,7,opt,name=StartBalancerMsg,proto3,oneof"`
}

type ServerMessage_StopBalancerMsg struct {
	StopBalancerMsg *StopBalancer `protobuf:"bytes,8,opt,name=StopBalancerMsg,proto3,oneof"`
}

type ServerMessage_StartBackupMsg struct {
	StartBackupMsg *StartBackup `protobuf:"bytes,9,opt,name=StartBackupMsg,proto3,oneof"`
}

type ServerMessage_CancelBackupMsg struct {
	CancelBackupMsg *CancelBackup `protobuf:"bytes,10,opt,name=CancelBackupMsg,proto3,oneof"`
}

type ServerMessage_StopOplogTailMsg struct {
	StopOplogTailMsg *StopOplogTail `protobuf:"bytes,11,opt,name=StopOplogTailMsg,proto3,oneof"`
}

type ServerMessage_RestoreBackupMsg struct {
	RestoreBackupMsg *RestoreBackup `protobuf:"bytes,12,opt,name=RestoreBackupMsg,proto3,oneof"`
}

func (*ServerMessage_AckMsg) isServerMessage_Payload() {}

func (*ServerMessage_BackupSourceMsg) isServerMessage_Payload() {}

func (*ServerMessage_GetStatusMsg) isServerMessage_Payload() {}

func (*ServerMessage_PingMsg) isServerMessage_Payload() {}

func (*ServerMessage_ErrorMsg) isServerMessage_Payload() {}

func (*ServerMessage_StartBalancerMsg) isServerMessage_Payload() {}

func (*ServerMessage_StopBalancerMsg) isServerMessage_Payload() {}

func (*ServerMessage_StartBackupMsg) isServerMessage_Payload() {}

func (*ServerMessage_CancelBackupMsg) isServerMessage_Payload() {}

func (*ServerMessage_StopOplogTailMsg) isServerMessage_Payload() {}

func (*ServerMessage_RestoreBackupMsg) isServerMessage_Payload() {}

func (m *ServerMessage) GetPayload() isServerMessage_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *ServerMessage) GetAckMsg() *Ack {
	if x, ok := m.GetPayload().(*ServerMessage_AckMsg); ok {
		return x.AckMsg
	}
	return nil
}

func (m *ServerMessage) GetBackupSourceMsg() *GetBackupSource {
	if x, ok := m.GetPayload().(*ServerMessage_BackupSourceMsg); ok {
		return x.BackupSourceMsg
	}
	return nil
}

func (m *ServerMessage) GetGetStatusMsg() *GetStatus {
	if x, ok := m.GetPayload().(*ServerMessage_GetStatusMsg); ok {
		return x.GetStatusMsg
	}
	return nil
}

func (m *ServerMessage) GetPingMsg() *Ping {
	if x, ok := m.GetPayload().(*ServerMessage_PingMsg); ok {
		return x.PingMsg
	}
	return nil
}

func (m *ServerMessage) GetErrorMsg() *Error {
	if x, ok := m.GetPayload().(*ServerMessage_ErrorMsg); ok {
		return x.ErrorMsg
	}
	return nil
}

func (m *ServerMessage) GetStartBalancerMsg() *StartBalancer {
	if x, ok := m.GetPayload().(*ServerMessage_StartBalancerMsg); ok {
		return x.StartBalancerMsg
	}
	return nil
}

func (m *ServerMessage) GetStopBalancerMsg() *StopBalancer {
	if x, ok := m.GetPayload().(*ServerMessage_StopBalancerMsg); ok {
		return x.StopBalancerMsg
	}
	return nil
}

func (m *ServerMessage) GetStartBackupMsg() *StartBackup {
	if x, ok := m.GetPayload().(*ServerMessage_StartBackupMsg); ok {
		return x.StartBackupMsg
	}
	return nil
}

func (m *ServerMessage) GetCancelBackupMsg() *CancelBackup {
	if x, ok := m.GetPayload().(*ServerMessage_CancelBackupMsg); ok {
		return x.CancelBackupMsg
	}
	return nil
}

func (m *ServerMessage) GetStopOplogTailMsg() *StopOplogTail {
	if x, ok := m.GetPayload().(*ServerMessage_StopOplogTailMsg); ok {
		return x.StopOplogTailMsg
	}
	return nil
}

func (m *ServerMessage) GetRestoreBackupMsg() *RestoreBackup {
	if x, ok := m.GetPayload().(*ServerMessage_RestoreBackupMsg); ok {
		return x.RestoreBackupMsg
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ServerMessage) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ServerMessage_OneofMarshaler, _ServerMessage_OneofUnmarshaler, _ServerMessage_OneofSizer, []interface{}{
		(*ServerMessage_AckMsg)(nil),
		(*ServerMessage_BackupSourceMsg)(nil),
		(*ServerMessage_GetStatusMsg)(nil),
		(*ServerMessage_PingMsg)(nil),
		(*ServerMessage_ErrorMsg)(nil),
		(*ServerMessage_StartBalancerMsg)(nil),
		(*ServerMessage_StopBalancerMsg)(nil),
		(*ServerMessage_StartBackupMsg)(nil),
		(*ServerMessage_CancelBackupMsg)(nil),
		(*ServerMessage_StopOplogTailMsg)(nil),
		(*ServerMessage_RestoreBackupMsg)(nil),
	}
}

func _ServerMessage_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ServerMessage)
	// Payload
	switch x := m.Payload.(type) {
	case *ServerMessage_AckMsg:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.AckMsg); err != nil {
			return err
		}
	case *ServerMessage_BackupSourceMsg:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BackupSourceMsg); err != nil {
			return err
		}
	case *ServerMessage_GetStatusMsg:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GetStatusMsg); err != nil {
			return err
		}
	case *ServerMessage_PingMsg:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PingMsg); err != nil {
			return err
		}
	case *ServerMessage_ErrorMsg:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ErrorMsg); err != nil {
			return err
		}
	case *ServerMessage_StartBalancerMsg:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.StartBalancerMsg); err != nil {
			return err
		}
	case *ServerMessage_StopBalancerMsg:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.StopBalancerMsg); err != nil {
			return err
		}
	case *ServerMessage_StartBackupMsg:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.StartBackupMsg); err != nil {
			return err
		}
	case *ServerMessage_CancelBackupMsg:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CancelBackupMsg); err != nil {
			return err
		}
	case *ServerMessage_StopOplogTailMsg:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.StopOplogTailMsg); err != nil {
			return err
		}
	case *ServerMessage_RestoreBackupMsg:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RestoreBackupMsg); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ServerMessage.Payload has unexpected type %T", x)
	}
	return nil
}

func _ServerMessage_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ServerMessage)
	switch tag {
	case 2: // Payload.AckMsg
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Ack)
		err := b.DecodeMessage(msg)
		m.Payload = &ServerMessage_AckMsg{msg}
		return true, err
	case 3: // Payload.BackupSourceMsg
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetBackupSource)
		err := b.DecodeMessage(msg)
		m.Payload = &ServerMessage_BackupSourceMsg{msg}
		return true, err
	case 4: // Payload.GetStatusMsg
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetStatus)
		err := b.DecodeMessage(msg)
		m.Payload = &ServerMessage_GetStatusMsg{msg}
		return true, err
	case 5: // Payload.PingMsg
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Ping)
		err := b.DecodeMessage(msg)
		m.Payload = &ServerMessage_PingMsg{msg}
		return true, err
	case 6: // Payload.ErrorMsg
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Error)
		err := b.DecodeMessage(msg)
		m.Payload = &ServerMessage_ErrorMsg{msg}
		return true, err
	case 7: // Payload.StartBalancerMsg
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(StartBalancer)
		err := b.DecodeMessage(msg)
		m.Payload = &ServerMessage_StartBalancerMsg{msg}
		return true, err
	case 8: // Payload.StopBalancerMsg
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(StopBalancer)
		err := b.DecodeMessage(msg)
		m.Payload = &ServerMessage_StopBalancerMsg{msg}
		return true, err
	case 9: // Payload.StartBackupMsg
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(StartBackup)
		err := b.DecodeMessage(msg)
		m.Payload = &ServerMessage_StartBackupMsg{msg}
		return true, err
	case 10: // Payload.CancelBackupMsg
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CancelBackup)
		err := b.DecodeMessage(msg)
		m.Payload = &ServerMessage_CancelBackupMsg{msg}
		return true, err
	case 11: // Payload.StopOplogTailMsg
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(StopOplogTail)
		err := b.DecodeMessage(msg)
		m.Payload = &ServerMessage_StopOplogTailMsg{msg}
		return true, err
	case 12: // Payload.RestoreBackupMsg
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RestoreBackup)
		err := b.DecodeMessage(msg)
		m.Payload = &ServerMessage_RestoreBackupMsg{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ServerMessage_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ServerMessage)
	// Payload
	switch x := m.Payload.(type) {
	case *ServerMessage_AckMsg:
		s := proto.Size(x.AckMsg)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ServerMessage_BackupSourceMsg:
		s := proto.Size(x.BackupSourceMsg)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ServerMessage_GetStatusMsg:
		s := proto.Size(x.GetStatusMsg)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ServerMessage_PingMsg:
		s := proto.Size(x.PingMsg)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ServerMessage_ErrorMsg:
		s := proto.Size(x.ErrorMsg)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ServerMessage_StartBalancerMsg:
		s := proto.Size(x.StartBalancerMsg)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ServerMessage_StopBalancerMsg:
		s := proto.Size(x.StopBalancerMsg)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ServerMessage_StartBackupMsg:
		s := proto.Size(x.StartBackupMsg)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ServerMessage_CancelBackupMsg:
		s := proto.Size(x.CancelBackupMsg)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ServerMessage_StopOplogTailMsg:
		s := proto.Size(x.StopOplogTailMsg)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ServerMessage_RestoreBackupMsg:
		s := proto.Size(x.RestoreBackupMsg)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ClientMessage struct {
	Version  int32  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	ClientID string `protobuf:"bytes,2,opt,name=clientID,proto3" json:"clientID,omitempty"`
	// Types that are valid to be assigned to Payload:
	//	*ClientMessage_AckMsg
	//	*ClientMessage_ErrorMsg
	//	*ClientMessage_BackupSourceMsg
	//	*ClientMessage_RegisterMsg
	//	*ClientMessage_PingMsg
	//	*ClientMessage_BackupFinishedMsg
	//	*ClientMessage_OplogFinishedMsg
	//	*ClientMessage_StatusMsg
	Payload              isClientMessage_Payload `protobuf_oneof:"Payload"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ClientMessage) Reset()         { *m = ClientMessage{} }
func (m *ClientMessage) String() string { return proto.CompactTextString(m) }
func (*ClientMessage) ProtoMessage()    {}
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_83994550f81e9f35, []int{17}
}

func (m *ClientMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientMessage.Unmarshal(m, b)
}
func (m *ClientMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientMessage.Marshal(b, m, deterministic)
}
func (m *ClientMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientMessage.Merge(m, src)
}
func (m *ClientMessage) XXX_Size() int {
	return xxx_messageInfo_ClientMessage.Size(m)
}
func (m *ClientMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ClientMessage proto.InternalMessageInfo

func (m *ClientMessage) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ClientMessage) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

type isClientMessage_Payload interface {
	isClientMessage_Payload()
}

type ClientMessage_AckMsg struct {
	AckMsg *Ack `protobuf:"bytes,3,opt,name=AckMsg,proto3,oneof"`
}

type ClientMessage_ErrorMsg struct {
	ErrorMsg *Error `protobuf:"bytes,4,opt,name=ErrorMsg,proto3,oneof"`
}

type ClientMessage_BackupSourceMsg struct {
	BackupSourceMsg *BackupSource `protobuf:"bytes,5,opt,name=BackupSourceMsg,proto3,oneof"`
}

type ClientMessage_RegisterMsg struct {
	RegisterMsg *Register `protobuf:"bytes,6,opt,name=RegisterMsg,proto3,oneof"`
}

type ClientMessage_PingMsg struct {
	PingMsg *Pong `protobuf:"bytes,7,opt,name=PingMsg,proto3,oneof"`
}

type ClientMessage_BackupFinishedMsg struct {
	BackupFinishedMsg *DBBackupFinishStatus `protobuf:"bytes,8,opt,name=BackupFinishedMsg,proto3,oneof"`
}

type ClientMessage_OplogFinishedMsg struct {
	OplogFinishedMsg *OplogBackupFinishStatus `protobuf:"bytes,9,opt,name=OplogFinishedMsg,proto3,oneof"`
}

type ClientMessage_StatusMsg struct {
	StatusMsg *Status `protobuf:"bytes,10,opt,name=StatusMsg,proto3,oneof"`
}

func (*ClientMessage_AckMsg) isClientMessage_Payload() {}

func (*ClientMessage_ErrorMsg) isClientMessage_Payload() {}

func (*ClientMessage_BackupSourceMsg) isClientMessage_Payload() {}

func (*ClientMessage_RegisterMsg) isClientMessage_Payload() {}

func (*ClientMessage_PingMsg) isClientMessage_Payload() {}

func (*ClientMessage_BackupFinishedMsg) isClientMessage_Payload() {}

func (*ClientMessage_OplogFinishedMsg) isClientMessage_Payload() {}

func (*ClientMessage_StatusMsg) isClientMessage_Payload() {}

func (m *ClientMessage) GetPayload() isClientMessage_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *ClientMessage) GetAckMsg() *Ack {
	if x, ok := m.GetPayload().(*ClientMessage_AckMsg); ok {
		return x.AckMsg
	}
	return nil
}

func (m *ClientMessage) GetErrorMsg() *Error {
	if x, ok := m.GetPayload().(*ClientMessage_ErrorMsg); ok {
		return x.ErrorMsg
	}
	return nil
}

func (m *ClientMessage) GetBackupSourceMsg() *BackupSource {
	if x, ok := m.GetPayload().(*ClientMessage_BackupSourceMsg); ok {
		return x.BackupSourceMsg
	}
	return nil
}

func (m *ClientMessage) GetRegisterMsg() *Register {
	if x, ok := m.GetPayload().(*ClientMessage_RegisterMsg); ok {
		return x.RegisterMsg
	}
	return nil
}

func (m *ClientMessage) GetPingMsg() *Pong {
	if x, ok := m.GetPayload().(*ClientMessage_PingMsg); ok {
		return x.PingMsg
	}
	return nil
}

func (m *ClientMessage) GetBackupFinishedMsg() *DBBackupFinishStatus {
	if x, ok := m.GetPayload().(*ClientMessage_BackupFinishedMsg); ok {
		return x.BackupFinishedMsg
	}
	return nil
}

func (m *ClientMessage) GetOplogFinishedMsg() *OplogBackupFinishStatus {
	if x, ok := m.GetPayload().(*ClientMessage_OplogFinishedMsg); ok {
		return x.OplogFinishedMsg
	}
	return nil
}

func (m *ClientMessage) GetStatusMsg() *Status {
	if x, ok := m.GetPayload().(*ClientMessage_StatusMsg); ok {
		return x.StatusMsg
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ClientMessage) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ClientMessage_OneofMarshaler, _ClientMessage_OneofUnmarshaler, _ClientMessage_OneofSizer, []interface{}{
		(*ClientMessage_AckMsg)(nil),
		(*ClientMessage_ErrorMsg)(nil),
		(*ClientMessage_BackupSourceMsg)(nil),
		(*ClientMessage_RegisterMsg)(nil),
		(*ClientMessage_PingMsg)(nil),
		(*ClientMessage_BackupFinishedMsg)(nil),
		(*ClientMessage_OplogFinishedMsg)(nil),
		(*ClientMessage_StatusMsg)(nil),
	}
}

func _ClientMessage_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ClientMessage)
	// Payload
	switch x := m.Payload.(type) {
	case *ClientMessage_AckMsg:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.AckMsg); err != nil {
			return err
		}
	case *ClientMessage_ErrorMsg:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ErrorMsg); err != nil {
			return err
		}
	case *ClientMessage_BackupSourceMsg:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BackupSourceMsg); err != nil {
			return err
		}
	case *ClientMessage_RegisterMsg:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RegisterMsg); err != nil {
			return err
		}
	case *ClientMessage_PingMsg:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PingMsg); err != nil {
			return err
		}
	case *ClientMessage_BackupFinishedMsg:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BackupFinishedMsg); err != nil {
			return err
		}
	case *ClientMessage_OplogFinishedMsg:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.OplogFinishedMsg); err != nil {
			return err
		}
	case *ClientMessage_StatusMsg:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.StatusMsg); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ClientMessage.Payload has unexpected type %T", x)
	}
	return nil
}

func _ClientMessage_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ClientMessage)
	switch tag {
	case 3: // Payload.AckMsg
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Ack)
		err := b.DecodeMessage(msg)
		m.Payload = &ClientMessage_AckMsg{msg}
		return true, err
	case 4: // Payload.ErrorMsg
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Error)
		err := b.DecodeMessage(msg)
		m.Payload = &ClientMessage_ErrorMsg{msg}
		return true, err
	case 5: // Payload.BackupSourceMsg
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BackupSource)
		err := b.DecodeMessage(msg)
		m.Payload = &ClientMessage_BackupSourceMsg{msg}
		return true, err
	case 6: // Payload.RegisterMsg
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Register)
		err := b.DecodeMessage(msg)
		m.Payload = &ClientMessage_RegisterMsg{msg}
		return true, err
	case 7: // Payload.PingMsg
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Pong)
		err := b.DecodeMessage(msg)
		m.Payload = &ClientMessage_PingMsg{msg}
		return true, err
	case 8: // Payload.BackupFinishedMsg
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DBBackupFinishStatus)
		err := b.DecodeMessage(msg)
		m.Payload = &ClientMessage_BackupFinishedMsg{msg}
		return true, err
	case 9: // Payload.OplogFinishedMsg
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(OplogBackupFinishStatus)
		err := b.DecodeMessage(msg)
		m.Payload = &ClientMessage_OplogFinishedMsg{msg}
		return true, err
	case 10: // Payload.StatusMsg
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Status)
		err := b.DecodeMessage(msg)
		m.Payload = &ClientMessage_StatusMsg{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ClientMessage_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ClientMessage)
	// Payload
	switch x := m.Payload.(type) {
	case *ClientMessage_AckMsg:
		s := proto.Size(x.AckMsg)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ClientMessage_ErrorMsg:
		s := proto.Size(x.ErrorMsg)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ClientMessage_BackupSourceMsg:
		s := proto.Size(x.BackupSourceMsg)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ClientMessage_RegisterMsg:
		s := proto.Size(x.RegisterMsg)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ClientMessage_PingMsg:
		s := proto.Size(x.PingMsg)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ClientMessage_BackupFinishedMsg:
		s := proto.Size(x.BackupFinishedMsg)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ClientMessage_OplogFinishedMsg:
		s := proto.Size(x.OplogFinishedMsg)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ClientMessage_StatusMsg:
		s := proto.Size(x.StatusMsg)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type BackupSource struct {
	SourceClient         string   `protobuf:"bytes,1,opt,name=SourceClient,proto3" json:"SourceClient,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackupSource) Reset()         { *m = BackupSource{} }
func (m *BackupSource) String() string { return proto.CompactTextString(m) }
func (*BackupSource) ProtoMessage()    {}
func (*BackupSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_83994550f81e9f35, []int{18}
}

func (m *BackupSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupSource.Unmarshal(m, b)
}
func (m *BackupSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupSource.Marshal(b, m, deterministic)
}
func (m *BackupSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupSource.Merge(m, src)
}
func (m *BackupSource) XXX_Size() int {
	return xxx_messageInfo_BackupSource.Size(m)
}
func (m *BackupSource) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupSource.DiscardUnknown(m)
}

var xxx_messageInfo_BackupSource proto.InternalMessageInfo

func (m *BackupSource) GetSourceClient() string {
	if m != nil {
		return m.SourceClient
	}
	return ""
}

type DBBackupFinishStatus struct {
	ClientID             string   `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	OK                   bool     `protobuf:"varint,2,opt,name=OK,proto3" json:"OK,omitempty"`
	Ts                   int64    `protobuf:"varint,3,opt,name=Ts,proto3" json:"Ts,omitempty"`
	Error                string   `protobuf:"bytes,4,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBBackupFinishStatus) Reset()         { *m = DBBackupFinishStatus{} }
func (m *DBBackupFinishStatus) String() string { return proto.CompactTextString(m) }
func (*DBBackupFinishStatus) ProtoMessage()    {}
func (*DBBackupFinishStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_83994550f81e9f35, []int{19}
}

func (m *DBBackupFinishStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBBackupFinishStatus.Unmarshal(m, b)
}
func (m *DBBackupFinishStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBBackupFinishStatus.Marshal(b, m, deterministic)
}
func (m *DBBackupFinishStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBBackupFinishStatus.Merge(m, src)
}
func (m *DBBackupFinishStatus) XXX_Size() int {
	return xxx_messageInfo_DBBackupFinishStatus.Size(m)
}
func (m *DBBackupFinishStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_DBBackupFinishStatus.DiscardUnknown(m)
}

var xxx_messageInfo_DBBackupFinishStatus proto.InternalMessageInfo

func (m *DBBackupFinishStatus) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *DBBackupFinishStatus) GetOK() bool {
	if m != nil {
		return m.OK
	}
	return false
}

func (m *DBBackupFinishStatus) GetTs() int64 {
	if m != nil {
		return m.Ts
	}
	return 0
}

func (m *DBBackupFinishStatus) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type OplogBackupFinishStatus struct {
	ClientID             string   `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	OK                   bool     `protobuf:"varint,2,opt,name=OK,proto3" json:"OK,omitempty"`
	Ts                   int64    `protobuf:"varint,3,opt,name=Ts,proto3" json:"Ts,omitempty"`
	Error                string   `protobuf:"bytes,4,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OplogBackupFinishStatus) Reset()         { *m = OplogBackupFinishStatus{} }
func (m *OplogBackupFinishStatus) String() string { return proto.CompactTextString(m) }
func (*OplogBackupFinishStatus) ProtoMessage()    {}
func (*OplogBackupFinishStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_83994550f81e9f35, []int{20}
}

func (m *OplogBackupFinishStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OplogBackupFinishStatus.Unmarshal(m, b)
}
func (m *OplogBackupFinishStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OplogBackupFinishStatus.Marshal(b, m, deterministic)
}
func (m *OplogBackupFinishStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OplogBackupFinishStatus.Merge(m, src)
}
func (m *OplogBackupFinishStatus) XXX_Size() int {
	return xxx_messageInfo_OplogBackupFinishStatus.Size(m)
}
func (m *OplogBackupFinishStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_OplogBackupFinishStatus.DiscardUnknown(m)
}

var xxx_messageInfo_OplogBackupFinishStatus proto.InternalMessageInfo

func (m *OplogBackupFinishStatus) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *OplogBackupFinishStatus) GetOK() bool {
	if m != nil {
		return m.OK
	}
	return false
}

func (m *OplogBackupFinishStatus) GetTs() int64 {
	if m != nil {
		return m.Ts
	}
	return 0
}

func (m *OplogBackupFinishStatus) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type Register struct {
	NodeType             NodeType `protobuf:"varint,1,opt,name=NodeType,proto3,enum=messages.NodeType" json:"NodeType,omitempty"`
	NodeName             string   `protobuf:"bytes,2,opt,name=NodeName,proto3" json:"NodeName,omitempty"`
	ClusterID            string   `protobuf:"bytes,3,opt,name=ClusterID,proto3" json:"ClusterID,omitempty"`
	ReplicasetID         string   `protobuf:"bytes,4,opt,name=ReplicasetID,proto3" json:"ReplicasetID,omitempty"`
	ReplicasetName       string   `protobuf:"bytes,5,opt,name=ReplicasetName,proto3" json:"ReplicasetName,omitempty"`
	BackupDir            string   `protobuf:"bytes,6,opt,name=BackupDir,proto3" json:"BackupDir,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Register) Reset()         { *m = Register{} }
func (m *Register) String() string { return proto.CompactTextString(m) }
func (*Register) ProtoMessage()    {}
func (*Register) Descriptor() ([]byte, []int) {
	return fileDescriptor_83994550f81e9f35, []int{21}
}

func (m *Register) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Register.Unmarshal(m, b)
}
func (m *Register) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Register.Marshal(b, m, deterministic)
}
func (m *Register) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Register.Merge(m, src)
}
func (m *Register) XXX_Size() int {
	return xxx_messageInfo_Register.Size(m)
}
func (m *Register) XXX_DiscardUnknown() {
	xxx_messageInfo_Register.DiscardUnknown(m)
}

var xxx_messageInfo_Register proto.InternalMessageInfo

func (m *Register) GetNodeType() NodeType {
	if m != nil {
		return m.NodeType
	}
	return NodeType_UNDEFINED
}

func (m *Register) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *Register) GetClusterID() string {
	if m != nil {
		return m.ClusterID
	}
	return ""
}

func (m *Register) GetReplicasetID() string {
	if m != nil {
		return m.ReplicasetID
	}
	return ""
}

func (m *Register) GetReplicasetName() string {
	if m != nil {
		return m.ReplicasetName
	}
	return ""
}

func (m *Register) GetBackupDir() string {
	if m != nil {
		return m.BackupDir
	}
	return ""
}

type Pong struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_83994550f81e9f35, []int{22}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type Status struct {
	RunningDBBackUp      bool            `protobuf:"varint,1,opt,name=RunningDBBackUp,proto3" json:"RunningDBBackUp,omitempty"`
	RunningOplogBackup   bool            `protobuf:"varint,2,opt,name=RunningOplogBackup,proto3" json:"RunningOplogBackup,omitempty"`
	RestoreStatus        RestoreStatus   `protobuf:"varint,3,opt,name=RestoreStatus,proto3,enum=messages.RestoreStatus" json:"RestoreStatus,omitempty"`
	BackupType           BackupType      `protobuf:"varint,4,opt,name=BackupType,proto3,enum=messages.BackupType" json:"BackupType,omitempty"`
	BytesSent            uint64          `protobuf:"varint,5,opt,name=BytesSent,proto3" json:"BytesSent,omitempty"`
	LastOplogTs          int64           `protobuf:"varint,6,opt,name=LastOplogTs,proto3" json:"LastOplogTs,omitempty"`
	BackupCompleted      int64           `protobuf:"varint,7,opt,name=BackupCompleted,proto3" json:"BackupCompleted,omitempty"`
	LastError            string          `protobuf:"bytes,8,opt,name=LastError,proto3" json:"LastError,omitempty"`
	ReplicasetVersion    uint64          `protobuf:"varint,9,opt,name=ReplicasetVersion,proto3" json:"ReplicasetVersion,omitempty"`
	DestinationType      DestinationType `protobuf:"varint,10,opt,name=DestinationType,proto3,enum=messages.DestinationType" json:"DestinationType,omitempty"`
	DestinationName      string          `protobuf:"bytes,11,opt,name=DestinationName,proto3" json:"DestinationName,omitempty"`
	DestinationDir       string          `protobuf:"bytes,12,opt,name=DestinationDir,proto3" json:"DestinationDir,omitempty"`
	CompressionType      CompressionType `protobuf:"varint,13,opt,name=CompressionType,proto3,enum=messages.CompressionType" json:"CompressionType,omitempty"`
	Cypher               Cypher          `protobuf:"varint,14,opt,name=Cypher,proto3,enum=messages.Cypher" json:"Cypher,omitempty"`
	StartOplogTs         int64           `protobuf:"varint,15,opt,name=StartOplogTs,proto3" json:"StartOplogTs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_83994550f81e9f35, []int{23}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetRunningDBBackUp() bool {
	if m != nil {
		return m.RunningDBBackUp
	}
	return false
}

func (m *Status) GetRunningOplogBackup() bool {
	if m != nil {
		return m.RunningOplogBackup
	}
	return false
}

func (m *Status) GetRestoreStatus() RestoreStatus {
	if m != nil {
		return m.RestoreStatus
	}
	return RestoreStatus_Not_Running
}

func (m *Status) GetBackupType() BackupType {
	if m != nil {
		return m.BackupType
	}
	return BackupType_LOGICAL
}

func (m *Status) GetBytesSent() uint64 {
	if m != nil {
		return m.BytesSent
	}
	return 0
}

func (m *Status) GetLastOplogTs() int64 {
	if m != nil {
		return m.LastOplogTs
	}
	return 0
}

func (m *Status) GetBackupCompleted() int64 {
	if m != nil {
		return m.BackupCompleted
	}
	return 0
}

func (m *Status) GetLastError() string {
	if m != nil {
		return m.LastError
	}
	return ""
}

func (m *Status) GetReplicasetVersion() uint64 {
	if m != nil {
		return m.ReplicasetVersion
	}
	return 0
}

func (m *Status) GetDestinationType() DestinationType {
	if m != nil {
		return m.DestinationType
	}
	return DestinationType_FILE
}

func (m *Status) GetDestinationName() string {
	if m != nil {
		return m.DestinationName
	}
	return ""
}

func (m *Status) GetDestinationDir() string {
	if m != nil {
		return m.DestinationDir
	}
	return ""
}

func (m *Status) GetCompressionType() CompressionType {
	if m != nil {
		return m.CompressionType
	}
	return CompressionType_NO_COMPRESSION
}

func (m *Status) GetCypher() Cypher {
	if m != nil {
		return m.Cypher
	}
	return Cypher_NO_CYPHER
}

func (m *Status) GetStartOplogTs() int64 {
	if m != nil {
		return m.StartOplogTs
	}
	return 0
}

func init() {
	proto.RegisterEnum("messages.ErrorType", ErrorType_name, ErrorType_value)
	proto.RegisterEnum("messages.BackupType", BackupType_name, BackupType_value)
	proto.RegisterEnum("messages.DestinationType", DestinationType_name, DestinationType_value)
	proto.RegisterEnum("messages.CompressionType", CompressionType_name, CompressionType_value)
	proto.RegisterEnum("messages.Cypher", Cypher_name, Cypher_value)
	proto.RegisterEnum("messages.NodeType", NodeType_name, NodeType_value)
	proto.RegisterEnum("messages.RestoreStatus", RestoreStatus_name, RestoreStatus_value)
	proto.RegisterType((*Ack)(nil), "messages.Ack")
	proto.RegisterType((*Empty)(nil), "messages.Empty")
	proto.RegisterType((*GetBackupSource)(nil), "messages.GetBackupSource")
	proto.RegisterType((*CancelBackup)(nil), "messages.CancelBackup")
	proto.RegisterType((*GetStatus)(nil), "messages.GetStatus")
	proto.RegisterType((*Ping)(nil), "messages.Ping")
	proto.RegisterType((*StartBalancer)(nil), "messages.StartBalancer")
	proto.RegisterType((*StopBalancer)(nil), "messages.StopBalancer")
	proto.RegisterType((*ReplicasetMetadata)(nil), "messages.ReplicasetMetadata")
	proto.RegisterType((*BackupMetadata)(nil), "messages.BackupMetadata")
	proto.RegisterMapType((map[string]*ReplicasetMetadata)(nil), "messages.BackupMetadata.ReplicasetsEntry")
	proto.RegisterType((*LogEntry)(nil), "messages.LogEntry")
	proto.RegisterType((*RestoreBackup)(nil), "messages.RestoreBackup")
	proto.RegisterType((*RestoreComplete)(nil), "messages.RestoreComplete")
	proto.RegisterType((*Error)(nil), "messages.Error")
	proto.RegisterType((*StartBackup)(nil), "messages.StartBackup")
	proto.RegisterType((*StopOplogTail)(nil), "messages.StopOplogTail")
	proto.RegisterType((*ServerMessage)(nil), "messages.ServerMessage")
	proto.RegisterType((*ClientMessage)(nil), "messages.ClientMessage")
	proto.RegisterType((*BackupSource)(nil), "messages.BackupSource")
	proto.RegisterType((*DBBackupFinishStatus)(nil), "messages.DBBackupFinishStatus")
	proto.RegisterType((*OplogBackupFinishStatus)(nil), "messages.OplogBackupFinishStatus")
	proto.RegisterType((*Register)(nil), "messages.Register")
	proto.RegisterType((*Pong)(nil), "messages.Pong")
	proto.RegisterType((*Status)(nil), "messages.Status")
}

func init() { proto.RegisterFile("messages/messages.proto", fileDescriptor_83994550f81e9f35) }

var fileDescriptor_83994550f81e9f35 = []byte{
	// 1851 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0xdd, 0x6e, 0xdb, 0xc8,
	0x15, 0x16, 0x45, 0xfd, 0x50, 0x47, 0x96, 0xc4, 0x8c, 0xdd, 0x46, 0x31, 0xd2, 0x6d, 0x96, 0x58,
	0x74, 0x55, 0xa3, 0xeb, 0x04, 0x6e, 0x50, 0x74, 0x5b, 0xb4, 0x85, 0x44, 0xd1, 0x96, 0x1a, 0x89,
	0x14, 0x86, 0xf2, 0x16, 0x09, 0x8a, 0x1a, 0x8c, 0x34, 0x2b, 0xb3, 0x96, 0x45, 0x82, 0xa4, 0x83,
	0xf5, 0xf3, 0xf4, 0x0d, 0x7a, 0xb3, 0x2f, 0x52, 0xa0, 0xbd, 0xea, 0x7d, 0xdf, 0xa2, 0x98, 0x19,
	0xfe, 0x0c, 0x49, 0x6d, 0x9c, 0x20, 0xd8, 0x3b, 0xce, 0x99, 0xef, 0x9c, 0x39, 0x3c, 0xf3, 0x9d,
	0x1f, 0x12, 0x1e, 0xdf, 0x92, 0x30, 0x74, 0x36, 0x24, 0x7c, 0x9e, 0x3c, 0x9c, 0xfa, 0x81, 0x17,
	0x79, 0x48, 0x49, 0xd6, 0x5a, 0x1d, 0xe4, 0xe1, 0xea, 0x46, 0x6b, 0x42, 0xdd, 0xb8, 0xf5, 0xa3,
	0x7b, 0xed, 0x11, 0xf4, 0x2e, 0x48, 0x34, 0x72, 0x56, 0x37, 0x77, 0xbe, 0xed, 0xdd, 0x05, 0x2b,
	0xa2, 0x75, 0xe1, 0x40, 0x77, 0x76, 0x2b, 0xb2, 0xe5, 0x52, 0xad, 0x0d, 0xad, 0x0b, 0x12, 0xd9,
	0x91, 0x13, 0xdd, 0x85, 0x5a, 0x03, 0x6a, 0x0b, 0x77, 0xb7, 0xd1, 0x7a, 0xd0, 0xb1, 0x23, 0x27,
	0x88, 0x46, 0xce, 0x96, 0x62, 0x03, 0xaa, 0x65, 0x47, 0x9e, 0x9f, 0xae, 0xff, 0x29, 0x01, 0xc2,
	0xc4, 0xdf, 0xba, 0x2b, 0x27, 0x24, 0xd1, 0x9c, 0x44, 0xce, 0xda, 0x89, 0x1c, 0xf4, 0x0b, 0xe8,
	0x66, 0xd2, 0xcb, 0xcb, 0xe9, 0xb8, 0x2f, 0x3d, 0x93, 0x06, 0x2d, 0x5c, 0x90, 0xe6, 0x71, 0xa6,
	0x73, 0x4b, 0xfa, 0xd5, 0x22, 0x8e, 0x4a, 0x91, 0x06, 0x07, 0xe3, 0x11, 0x77, 0x94, 0xa1, 0x64,
	0x86, 0xca, 0xc9, 0xd0, 0x00, 0x7a, 0x96, 0xbf, 0xf5, 0x36, 0x02, 0xac, 0xc6, 0x60, 0x45, 0xb1,
	0xf6, 0xbf, 0x1a, 0x74, 0xf9, 0x32, 0x75, 0xb8, 0x0f, 0x4d, 0xf6, 0xa2, 0xcb, 0x90, 0x79, 0x2a,
	0xe3, 0x64, 0x89, 0x8e, 0xa0, 0x6e, 0xec, 0xd6, 0xcb, 0x90, 0x79, 0x26, 0x63, 0xbe, 0x40, 0x2f,
	0x01, 0xb8, 0x85, 0xe5, 0xbd, 0xcf, 0xdd, 0xe9, 0x9e, 0x1d, 0x9d, 0xa6, 0xf7, 0x91, 0xed, 0x61,
	0x01, 0x47, 0x5f, 0x97, 0xf9, 0xc2, 0x6d, 0xbb, 0xb1, 0x87, 0x32, 0x2e, 0x48, 0xd1, 0x33, 0x68,
	0xcf, 0x9c, 0x30, 0x62, 0xd2, 0x65, 0xd8, 0xaf, 0x33, 0x90, 0x28, 0x42, 0x3a, 0xf4, 0xc6, 0x24,
	0x8c, 0xdc, 0x9d, 0x13, 0xb9, 0xde, 0x8e, 0x39, 0xd1, 0x60, 0x4e, 0x3c, 0xc9, 0x9c, 0x28, 0x00,
	0x70, 0x51, 0x83, 0xba, 0x23, 0x88, 0xc6, 0x6e, 0xd0, 0x6f, 0xf2, 0xe8, 0xe7, 0xa5, 0x68, 0x00,
	0x0d, 0xfd, 0xde, 0xbf, 0x26, 0x41, 0x5f, 0x61, 0x67, 0xa8, 0xd9, 0x19, 0x5c, 0x8e, 0xe3, 0x7d,
	0xea, 0x96, 0xee, 0xdd, 0xfa, 0x01, 0x09, 0xc3, 0xc4, 0xad, 0x56, 0xd1, 0xad, 0x02, 0x00, 0x17,
	0x35, 0xe8, 0xdb, 0x8f, 0x49, 0xb8, 0x0a, 0x5c, 0x9f, 0x3a, 0xd0, 0x07, 0xe6, 0x93, 0x28, 0x42,
	0xaf, 0xa0, 0x9d, 0x11, 0x24, 0xec, 0xb7, 0x9f, 0xc9, 0x83, 0xf6, 0xd9, 0x2f, 0x8b, 0xe1, 0x4f,
	0x2e, 0xf7, 0x54, 0xc0, 0x1a, 0xbb, 0x28, 0xb8, 0xc7, 0xa2, 0xf6, 0xf1, 0x5f, 0x41, 0x2d, 0x02,
	0x90, 0x0a, 0xf2, 0x0d, 0xb9, 0x8f, 0x49, 0x4b, 0x1f, 0xd1, 0x19, 0xd4, 0xdf, 0x39, 0xdb, 0x3b,
	0x4e, 0xd0, 0xf6, 0xd9, 0xd3, 0xec, 0xb0, 0x32, 0xfd, 0x31, 0x87, 0xfe, 0xae, 0xfa, 0x5b, 0x49,
	0xfb, 0x16, 0x94, 0x99, 0xb7, 0xe1, 0x56, 0x8f, 0x41, 0xd1, 0xb7, 0x2e, 0xd9, 0x45, 0x69, 0x3e,
	0xa4, 0x6b, 0x4a, 0xb3, 0x19, 0x79, 0x47, 0xb6, 0xcc, 0x7e, 0x07, 0xf3, 0x05, 0xea, 0x42, 0x75,
	0x19, 0x32, 0x7a, 0xc9, 0xb8, 0xba, 0x0c, 0x29, 0x4d, 0xe7, 0xfc, 0xdc, 0x98, 0xdb, 0xc9, 0x52,
	0xfb, 0x5e, 0x86, 0x0e, 0x26, 0x61, 0xe4, 0x05, 0x84, 0xbf, 0x7d, 0x81, 0xa2, 0xd2, 0x07, 0x52,
	0xf4, 0x6b, 0x00, 0x5e, 0x20, 0x98, 0x56, 0xf5, 0x21, 0x4e, 0x09, 0x60, 0x9a, 0xa4, 0x7c, 0x35,
	0xba, 0x5b, 0xdd, 0x90, 0x28, 0x49, 0x52, 0x51, 0xc6, 0x13, 0x99, 0x4b, 0x84, 0x0c, 0xcd, 0xc9,
	0xd2, 0x44, 0x16, 0x60, 0x75, 0x21, 0x91, 0x05, 0xe4, 0x1e, 0xba, 0x35, 0x3e, 0x9a, 0x6e, 0x19,
	0xbb, 0x9b, 0x0f, 0xb0, 0xbb, 0x9c, 0xbe, 0xca, 0xde, 0xf4, 0xfd, 0x15, 0x3c, 0xb2, 0x6f, 0x5c,
	0xff, 0x32, 0x24, 0x41, 0x38, 0xdc, 0xad, 0xb1, 0xb7, 0x25, 0x21, 0xcb, 0x03, 0x05, 0x97, 0x37,
	0xb4, 0x05, 0xf4, 0xe2, 0x8b, 0xa3, 0x9e, 0x6d, 0x49, 0x44, 0xde, 0x4b, 0x94, 0xcf, 0x41, 0x36,
	0x82, 0x20, 0xa6, 0x61, 0x2f, 0xf3, 0xd5, 0x08, 0x02, 0x2f, 0xc0, 0x74, 0x4f, 0xfb, 0x33, 0xd4,
	0xd9, 0x4a, 0xa4, 0x8b, 0x94, 0xa3, 0x0b, 0xfa, 0x12, 0x6a, 0xba, 0xb7, 0x4e, 0x2e, 0xf8, 0xb0,
	0x60, 0x86, 0x05, 0x8a, 0x01, 0xb4, 0x7f, 0xcb, 0xd0, 0x8e, 0x5b, 0xc0, 0x27, 0xb0, 0x6a, 0x4f,
	0xb9, 0xaa, 0x7e, 0x74, 0xb9, 0xfa, 0x0c, 0x80, 0xde, 0xfa, 0x22, 0x20, 0xdf, 0xba, 0xdf, 0xc5,
	0xec, 0x12, 0x24, 0xa5, 0x26, 0x51, 0xfb, 0xb0, 0x26, 0x51, 0xdf, 0xdb, 0x24, 0xf6, 0x14, 0xc7,
	0xc6, 0xde, 0xe2, 0xb8, 0x87, 0x83, 0xcd, 0x4f, 0xe0, 0xa0, 0xf2, 0xd1, 0x1c, 0x6c, 0xfd, 0x50,
	0x0b, 0x79, 0x7f, 0x11, 0xd5, 0x7e, 0x4e, 0x7b, 0xbb, 0xe7, 0xf3, 0x8e, 0xe2, 0xb8, 0x49, 0xb1,
	0x91, 0x92, 0x62, 0xa3, 0xfd, 0xa7, 0x0e, 0x1d, 0x9b, 0x04, 0xef, 0x48, 0x90, 0xb0, 0xa6, 0x0f,
	0xcd, 0x77, 0x24, 0xa0, 0x5e, 0x33, 0x58, 0x1d, 0x27, 0x4b, 0xf4, 0x25, 0x34, 0x86, 0xab, 0x9b,
	0x79, 0xb8, 0x89, 0x89, 0xd9, 0xc9, 0x5e, 0x60, 0xb8, 0xba, 0x99, 0x54, 0x70, 0xbc, 0x8d, 0x0c,
	0xe8, 0x89, 0x63, 0x08, 0xd5, 0x90, 0x99, 0x86, 0x10, 0xae, 0xc2, 0xa8, 0x32, 0xa9, 0xe0, 0xa2,
	0x0e, 0xfa, 0x1a, 0x0e, 0xd2, 0x69, 0x85, 0xda, 0xa8, 0x31, 0x1b, 0x87, 0x39, 0x1b, 0x7c, 0x77,
	0x52, 0xc1, 0x39, 0x28, 0x3a, 0x81, 0x26, 0x9d, 0x6d, 0xa8, 0x56, 0x9d, 0x69, 0x75, 0x33, 0x2d,
	0xba, 0x31, 0xa9, 0xe0, 0x04, 0x80, 0xbe, 0x02, 0x85, 0x25, 0x04, 0x05, 0x37, 0xf6, 0x66, 0xdc,
	0xa4, 0x82, 0x53, 0x08, 0x32, 0x40, 0xcd, 0x8d, 0x4b, 0x54, 0xad, 0xc9, 0xd4, 0x1e, 0x67, 0x6a,
	0x39, 0xc4, 0xa4, 0x82, 0x4b, 0x2a, 0x68, 0x04, 0x3d, 0x71, 0xc8, 0xa2, 0x56, 0x14, 0x66, 0xe5,
	0xa7, 0xa2, 0x95, 0x0c, 0x40, 0x03, 0x54, 0x50, 0x40, 0x7f, 0x82, 0xae, 0x90, 0xb6, 0xd4, 0x44,
	0x8b, 0x99, 0xf8, 0x49, 0xc9, 0x11, 0xba, 0x3f, 0xa9, 0xe0, 0x02, 0x9c, 0x3a, 0x21, 0xce, 0x87,
	0xd4, 0x02, 0x14, 0x9d, 0x10, 0x01, 0xd4, 0x89, 0x82, 0x02, 0x8f, 0x87, 0x40, 0x31, 0x6a, 0xa4,
	0x5d, 0x8e, 0x87, 0x80, 0xe0, 0xf1, 0xc8, 0xab, 0x50, 0x33, 0xb9, 0xd6, 0x46, 0xcd, 0x1c, 0x14,
	0xcd, 0xe4, 0x10, 0xd4, 0x4c, 0x51, 0x65, 0xd4, 0x82, 0xe6, 0xc2, 0xb9, 0xdf, 0x7a, 0xce, 0x5a,
	0xfb, 0x47, 0x0d, 0x3a, 0xbc, 0xa2, 0x3e, 0x4c, 0xed, 0x63, 0x50, 0x56, 0x49, 0x31, 0xe6, 0xd3,
	0x69, 0xba, 0x16, 0x68, 0x2f, 0xbf, 0x9f, 0xf6, 0x22, 0x91, 0x6a, 0x0f, 0x13, 0x69, 0x54, 0xce,
	0x92, 0x7a, 0x31, 0xf8, 0x0f, 0xa5, 0xc8, 0x6f, 0xe8, 0x90, 0xb4, 0x71, 0xc3, 0x88, 0x08, 0xf4,
	0x45, 0x62, 0xc0, 0xf8, 0xe6, 0xa4, 0x82, 0x45, 0xa0, 0x98, 0x1f, 0xcd, 0x52, 0x7e, 0x78, 0xf9,
	0xfc, 0x30, 0xe1, 0x11, 0x3f, 0xf6, 0xdc, 0xdd, 0xb9, 0xe1, 0x35, 0x59, 0x67, 0x5c, 0xfd, 0x4c,
	0xa8, 0xec, 0x23, 0x11, 0x94, 0xa6, 0x65, 0x59, 0x15, 0x59, 0xa0, 0xb2, 0x9b, 0x17, 0xcd, 0x71,
	0xde, 0x7e, 0x9e, 0x99, 0x13, 0x2a, 0x75, 0xc1, 0x62, 0x49, 0x19, 0xbd, 0x80, 0x56, 0x56, 0x24,
	0x38, 0x7f, 0xd5, 0x5c, 0x06, 0x70, 0xc5, 0x0c, 0x24, 0xb2, 0xe4, 0x0c, 0x0e, 0xc4, 0xa0, 0x66,
	0x03, 0x0e, 0xa7, 0x4e, 0xdc, 0x53, 0x73, 0x32, 0xed, 0x1a, 0x8e, 0xf6, 0xbd, 0xee, 0x7b, 0x5b,
	0x7a, 0x17, 0xaa, 0xd6, 0x2b, 0xc6, 0x2d, 0x05, 0x57, 0xad, 0x57, 0xa5, 0xa9, 0xef, 0x28, 0xee,
	0xe7, 0x71, 0x47, 0xe3, 0x0b, 0xed, 0x06, 0x1e, 0xff, 0x40, 0x24, 0x7e, 0x84, 0xc3, 0xfe, 0x2b,
	0x81, 0x92, 0x90, 0x04, 0x9d, 0x82, 0x62, 0x7a, 0x6b, 0x22, 0x4c, 0x00, 0x02, 0xad, 0x92, 0x1d,
	0x9c, 0x62, 0xa8, 0x3b, 0xf4, 0x59, 0xf8, 0xbe, 0x4b, 0xd7, 0xe8, 0x29, 0xb4, 0xf4, 0xed, 0x1d,
	0x35, 0x3b, 0x1d, 0xc7, 0x3d, 0x3d, 0x13, 0xd0, 0x88, 0x67, 0xe3, 0xf5, 0x74, 0x9c, 0xb4, 0x74,
	0x51, 0xb6, 0xe7, 0x1b, 0xb2, 0xbe, 0xf7, 0x1b, 0xf2, 0x29, 0xb4, 0x78, 0xa8, 0xb2, 0x5e, 0x9e,
	0x09, 0xb4, 0x2f, 0xa0, 0x46, 0xc9, 0x4d, 0x51, 0xb4, 0x7f, 0x86, 0x91, 0x73, 0xeb, 0xc7, 0xbd,
	0x30, 0x13, 0x68, 0xdf, 0xd7, 0xa1, 0x11, 0xc7, 0x78, 0x00, 0x3d, 0x7c, 0xb7, 0xdb, 0xb9, 0xbb,
	0x0d, 0xbf, 0xef, 0x4b, 0x0e, 0x57, 0x70, 0x51, 0x8c, 0x4e, 0x01, 0xc5, 0x22, 0xe1, 0xbe, 0xe2,
	0x1b, 0xd8, 0xb3, 0x83, 0xfe, 0x90, 0x4e, 0xf2, 0xfc, 0xa8, 0xf8, 0xf3, 0xb2, 0x5c, 0xeb, 0xf8,
	0x36, 0xce, 0xa3, 0x0b, 0x13, 0x5a, 0xed, 0x03, 0x27, 0x34, 0x1a, 0x9d, 0xfb, 0x88, 0x84, 0x36,
	0x25, 0x36, 0x0d, 0x60, 0x0d, 0x67, 0x82, 0xe2, 0x07, 0x69, 0xa3, 0xfc, 0x41, 0x3a, 0x48, 0x2a,
	0x56, 0x32, 0xc4, 0xae, 0x59, 0xf5, 0x90, 0x71, 0x51, 0x4c, 0x4f, 0xa2, 0x8a, 0x9c, 0x64, 0x0a,
	0xbf, 0x87, 0x54, 0x40, 0x67, 0xe7, 0xec, 0xde, 0xbe, 0x89, 0x2b, 0x72, 0x8b, 0xf9, 0x53, 0xde,
	0xd8, 0x37, 0x57, 0xc2, 0x47, 0xcf, 0x95, 0x83, 0x9c, 0x11, 0xc6, 0xa0, 0x36, 0x9f, 0x09, 0x0b,
	0xe2, 0x3d, 0x33, 0xe1, 0xc1, 0x87, 0xce, 0x84, 0x9d, 0x4f, 0x98, 0x09, 0xbb, 0x0f, 0xcc, 0x84,
	0xb4, 0x2e, 0xd1, 0xe6, 0x9d, 0x5c, 0x4f, 0x8f, 0x05, 0x3e, 0x27, 0x3b, 0xf9, 0x3b, 0xb4, 0xd2,
	0xd1, 0x1e, 0x1d, 0x80, 0x62, 0x5a, 0x57, 0x06, 0xc6, 0x16, 0x56, 0x2b, 0xe8, 0x31, 0x1c, 0x9a,
	0xd6, 0xf2, 0x6a, 0x3a, 0x5f, 0xcc, 0x8c, 0xb9, 0x61, 0x2e, 0x8d, 0xf1, 0xd5, 0x6b, 0x63, 0xa9,
	0x4a, 0x74, 0x43, 0xb7, 0xe6, 0xf3, 0x4b, 0x73, 0xaa, 0x0f, 0x97, 0x53, 0xcb, 0x8c, 0x35, 0xaa,
	0xe8, 0x67, 0xf0, 0x44, 0x9f, 0x4d, 0x0d, 0x73, 0x79, 0x35, 0x9c, 0x61, 0x63, 0x38, 0x7e, 0x7d,
	0x85, 0x8d, 0x8b, 0xa9, 0xbd, 0x34, 0xb0, 0x31, 0x56, 0xe5, 0x93, 0x81, 0xc8, 0x40, 0xd4, 0x86,
	0xe6, 0xcc, 0xba, 0x98, 0xea, 0xc3, 0x99, 0x5a, 0x41, 0x1d, 0x68, 0x4d, 0xac, 0xe5, 0x68, 0xa8,
	0xbf, 0xba, 0x5c, 0xa8, 0xd2, 0xc9, 0x17, 0xa5, 0xfb, 0x43, 0x0a, 0xd4, 0xce, 0xa7, 0x33, 0x43,
	0xad, 0xa0, 0x26, 0xc8, 0xc3, 0xbf, 0xd8, 0xaa, 0x74, 0x32, 0x2e, 0x85, 0x13, 0x21, 0xe8, 0x9a,
	0xd6, 0x95, 0x6e, 0xcd, 0x17, 0xd8, 0xb0, 0xed, 0xa9, 0x65, 0xaa, 0x15, 0xaa, 0x79, 0xf1, 0x66,
	0xba, 0x50, 0x25, 0x04, 0xd0, 0xb0, 0xcd, 0xe1, 0x62, 0xf1, 0x5a, 0xad, 0x52, 0x2b, 0xb3, 0x37,
	0x2f, 0x55, 0xf9, 0xe4, 0xf7, 0x49, 0x3c, 0xa9, 0x13, 0x54, 0xf9, 0xf5, 0x62, 0x62, 0xe0, 0xf8,
	0x1c, 0xc3, 0x56, 0x25, 0xfa, 0x30, 0x36, 0x6c, 0xae, 0x83, 0xf5, 0x97, 0xaa, 0xcc, 0x1e, 0xec,
	0xa1, 0x5a, 0x3b, 0xf1, 0xb3, 0x92, 0x47, 0xd5, 0x2f, 0xcd, 0xb1, 0x71, 0x3e, 0x35, 0x8d, 0xb1,
	0x5a, 0xa1, 0x87, 0xcd, 0x2d, 0xf3, 0xc2, 0x1a, 0xab, 0x12, 0x75, 0x8b, 0x3f, 0x5f, 0x61, 0x63,
	0x31, 0xb3, 0x8d, 0xa5, 0x5a, 0x45, 0x87, 0xd0, 0x8b, 0x65, 0xf6, 0x64, 0x88, 0xc7, 0xf6, 0x37,
	0x58, 0x95, 0xd1, 0x11, 0xa8, 0xb1, 0x50, 0xb7, 0xcc, 0xf3, 0xe9, 0x05, 0x95, 0xd6, 0x52, 0x53,
	0xb6, 0x5a, 0x3f, 0x31, 0x0a, 0x55, 0x00, 0xf5, 0xa0, 0x6d, 0x7a, 0xd1, 0x55, 0x5c, 0x30, 0xd4,
	0x0a, 0x15, 0x70, 0x04, 0x2b, 0x36, 0xfc, 0xf4, 0x54, 0xc0, 0xee, 0x5d, 0xad, 0x9e, 0xfd, 0xab,
	0x0a, 0x4a, 0x3c, 0xe3, 0x84, 0xe8, 0x05, 0x34, 0x67, 0xde, 0x66, 0xe3, 0xee, 0x36, 0x48, 0xa8,
	0xd8, 0xc9, 0xff, 0x89, 0xe3, 0xfc, 0xf4, 0xa2, 0x55, 0x06, 0x12, 0x3a, 0x87, 0x83, 0x44, 0x5b,
	0xbf, 0x76, 0x22, 0x24, 0x14, 0xa1, 0xdc, 0xfc, 0x74, 0x2c, 0x0e, 0x74, 0xe2, 0x37, 0x03, 0xb5,
	0xf2, 0x42, 0x42, 0x3a, 0xa8, 0xf9, 0xb6, 0x48, 0xd6, 0xe8, 0x81, 0x09, 0xa1, 0xe4, 0x0e, 0x9a,
	0xc2, 0x61, 0xa9, 0xe3, 0x91, 0x35, 0x7a, 0x78, 0x34, 0x28, 0x9b, 0xfa, 0x63, 0x3a, 0x52, 0x66,
	0x85, 0xe9, 0x49, 0xa9, 0xc0, 0x26, 0x7b, 0x25, 0xfd, 0xd1, 0xdf, 0xe0, 0x89, 0xeb, 0x9d, 0x6e,
	0x02, 0x7f, 0x75, 0x4a, 0xbe, 0x73, 0x28, 0x2a, 0x4c, 0x21, 0xa3, 0x4e, 0x12, 0xb2, 0x45, 0xe0,
	0x45, 0xde, 0x42, 0x7a, 0xf3, 0x62, 0xe3, 0x46, 0xd7, 0x77, 0x6f, 0x4f, 0x57, 0xde, 0xed, 0x73,
	0x9f, 0x04, 0x2b, 0x6f, 0xe7, 0x3c, 0xbf, 0xf5, 0x76, 0x1b, 0x6f, 0xfd, 0xf6, 0xab, 0xb7, 0xcc,
	0xdb, 0xe7, 0xec, 0x0f, 0x6e, 0xfa, 0x43, 0xf7, 0x6d, 0x83, 0xad, 0x7f, 0xfd, 0xff, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x41, 0x9a, 0x9d, 0xcf, 0xec, 0x15, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MessagesClient is the client API for Messages service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MessagesClient interface {
	// streams
	Logging(ctx context.Context, opts ...grpc.CallOption) (Messages_LoggingClient, error)
	MessagesChat(ctx context.Context, opts ...grpc.CallOption) (Messages_MessagesChatClient, error)
	// Invidividual responses
	DBBackupFinished(ctx context.Context, in *DBBackupFinishStatus, opts ...grpc.CallOption) (*Ack, error)
	OplogBackupFinished(ctx context.Context, in *OplogBackupFinishStatus, opts ...grpc.CallOption) (*Ack, error)
	RestoreCompleted(ctx context.Context, in *RestoreComplete, opts ...grpc.CallOption) (*Ack, error)
}

type messagesClient struct {
	cc *grpc.ClientConn
}

func NewMessagesClient(cc *grpc.ClientConn) MessagesClient {
	return &messagesClient{cc}
}

func (c *messagesClient) Logging(ctx context.Context, opts ...grpc.CallOption) (Messages_LoggingClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Messages_serviceDesc.Streams[0], "/messages.Messages/Logging", opts...)
	if err != nil {
		return nil, err
	}
	x := &messagesLoggingClient{stream}
	return x, nil
}

type Messages_LoggingClient interface {
	Send(*LogEntry) error
	CloseAndRecv() (*Ack, error)
	grpc.ClientStream
}

type messagesLoggingClient struct {
	grpc.ClientStream
}

func (x *messagesLoggingClient) Send(m *LogEntry) error {
	return x.ClientStream.SendMsg(m)
}

func (x *messagesLoggingClient) CloseAndRecv() (*Ack, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Ack)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *messagesClient) MessagesChat(ctx context.Context, opts ...grpc.CallOption) (Messages_MessagesChatClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Messages_serviceDesc.Streams[1], "/messages.Messages/MessagesChat", opts...)
	if err != nil {
		return nil, err
	}
	x := &messagesMessagesChatClient{stream}
	return x, nil
}

type Messages_MessagesChatClient interface {
	Send(*ClientMessage) error
	Recv() (*ServerMessage, error)
	grpc.ClientStream
}

type messagesMessagesChatClient struct {
	grpc.ClientStream
}

func (x *messagesMessagesChatClient) Send(m *ClientMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *messagesMessagesChatClient) Recv() (*ServerMessage, error) {
	m := new(ServerMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *messagesClient) DBBackupFinished(ctx context.Context, in *DBBackupFinishStatus, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, "/messages.Messages/DBBackupFinished", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagesClient) OplogBackupFinished(ctx context.Context, in *OplogBackupFinishStatus, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, "/messages.Messages/OplogBackupFinished", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagesClient) RestoreCompleted(ctx context.Context, in *RestoreComplete, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, "/messages.Messages/RestoreCompleted", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessagesServer is the server API for Messages service.
type MessagesServer interface {
	// streams
	Logging(Messages_LoggingServer) error
	MessagesChat(Messages_MessagesChatServer) error
	// Invidividual responses
	DBBackupFinished(context.Context, *DBBackupFinishStatus) (*Ack, error)
	OplogBackupFinished(context.Context, *OplogBackupFinishStatus) (*Ack, error)
	RestoreCompleted(context.Context, *RestoreComplete) (*Ack, error)
}

func RegisterMessagesServer(s *grpc.Server, srv MessagesServer) {
	s.RegisterService(&_Messages_serviceDesc, srv)
}

func _Messages_Logging_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MessagesServer).Logging(&messagesLoggingServer{stream})
}

type Messages_LoggingServer interface {
	SendAndClose(*Ack) error
	Recv() (*LogEntry, error)
	grpc.ServerStream
}

type messagesLoggingServer struct {
	grpc.ServerStream
}

func (x *messagesLoggingServer) SendAndClose(m *Ack) error {
	return x.ServerStream.SendMsg(m)
}

func (x *messagesLoggingServer) Recv() (*LogEntry, error) {
	m := new(LogEntry)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Messages_MessagesChat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MessagesServer).MessagesChat(&messagesMessagesChatServer{stream})
}

type Messages_MessagesChatServer interface {
	Send(*ServerMessage) error
	Recv() (*ClientMessage, error)
	grpc.ServerStream
}

type messagesMessagesChatServer struct {
	grpc.ServerStream
}

func (x *messagesMessagesChatServer) Send(m *ServerMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *messagesMessagesChatServer) Recv() (*ClientMessage, error) {
	m := new(ClientMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Messages_DBBackupFinished_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DBBackupFinishStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagesServer).DBBackupFinished(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messages.Messages/DBBackupFinished",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagesServer).DBBackupFinished(ctx, req.(*DBBackupFinishStatus))
	}
	return interceptor(ctx, in, info, handler)
}

func _Messages_OplogBackupFinished_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OplogBackupFinishStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagesServer).OplogBackupFinished(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messages.Messages/OplogBackupFinished",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagesServer).OplogBackupFinished(ctx, req.(*OplogBackupFinishStatus))
	}
	return interceptor(ctx, in, info, handler)
}

func _Messages_RestoreCompleted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreComplete)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagesServer).RestoreCompleted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messages.Messages/RestoreCompleted",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagesServer).RestoreCompleted(ctx, req.(*RestoreComplete))
	}
	return interceptor(ctx, in, info, handler)
}

var _Messages_serviceDesc = grpc.ServiceDesc{
	ServiceName: "messages.Messages",
	HandlerType: (*MessagesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DBBackupFinished",
			Handler:    _Messages_DBBackupFinished_Handler,
		},
		{
			MethodName: "OplogBackupFinished",
			Handler:    _Messages_OplogBackupFinished_Handler,
		},
		{
			MethodName: "RestoreCompleted",
			Handler:    _Messages_RestoreCompleted_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Logging",
			Handler:       _Messages_Logging_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "MessagesChat",
			Handler:       _Messages_MessagesChat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "messages/messages.proto",
}
