#FROM golang:1.11-alpine
FROM golang:1.11-stretch

RUN apt-get update && apt-get install -y upx-ucl
#RUN apk add git make upx

WORKDIR /go/src/github.com/percona/mongodb-backup
COPY . .

RUN make vendor
CMD make DEST_DIR=/release install
