#!/usr/bin/env bash

set -o errexit
set -o xtrace


test_dir=$(realpath $(dirname $0))
. ${test_dir}/functions

MONGO_VERSION=${MONGODB_VERSION:-"4.2"}

desc 'RUN SHARDED CLUTER TESTS'

run $COMPOSE_PATH $MONGO_VERSION