services:
  tests:
    build:
      dockerfile: ./e2e-tests/docker/tests.dockerfile
      context: ../..
      args:
        - TESTS_BCP_TYPE=logical
    command: pbm-test
    environment:
      - BACKUP_USER=bcp
      - MONGO_PASS=test1234
      - TESTS_TYPE=remapping
    volumes:
      - ./conf:/etc/pbm
      - ./backups:/opt/backups

  docker-host:
    image: alpine/socat
    volumes: [/var/run/docker.sock:/var/run/docker.sock]
    command: "tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock"

  rs101:
    build:
      dockerfile: ./e2e-tests/docker/mongodb.dockerfile
      context: ../..
      args:
        - MONGODB_VERSION=${MONGODB_VERSION:-5.0}
        - MONGODB_IMAGE=${MONGODB_IMAGE:-percona/percona-server-mongodb}
    hostname: rs101
    labels:
      - "com.percona.pbm.app=mongod"
    environment:
      - REPLSET_NAME=rs1
      - MONGO_USER=dba
      - BACKUP_USER=bcp
      - MONGO_PASS=test1234
      - SINGLE_NODE=true
    command: mongod --replSet rs1 --port 27017 --storageEngine wiredTiger --keyFile /opt/keyFile --wiredTigerCacheSizeGB 1
    volumes:
      - data-rs101:/data/db
      - ./scripts/start.sh:/opt/start.sh

  agent-rs101:
    container_name: "pbmagent_rs101"
    user: "1001"
    labels:
      - "com.percona.pbm.app=agent"
      - "com.percona.pbm.agent.rs=rs1"
    environment:
      - "PBM_MONGODB_URI=mongodb://${BACKUP_USER:-bcp}:${MONGO_PASS:-test1234}@rs101:27017"
    build:
      labels:
        - "com.percona.pbm.app=agent"
      dockerfile: ./e2e-tests/docker/pbm.dockerfile
      context: ../..
      args:
        - MONGODB_VERSION=${MONGODB_VERSION:-5.0}
        - MONGODB_IMAGE=${MONGODB_IMAGE:-percona/percona-server-mongodb}
    volumes:
      - ./conf:/etc/pbm
      - ./backups:/opt/backups
      - data-rs101:/data/db
    command: pbm-agent
    cap_add:
      - NET_ADMIN

  rs201:
    build:
      dockerfile: ./e2e-tests/docker/mongodb.dockerfile
      context: ../..
      args:
        - MONGODB_VERSION=${MONGODB_VERSION:-5.0}
        - MONGODB_IMAGE=${MONGODB_IMAGE:-percona/percona-server-mongodb}
    hostname: rs201
    labels:
      - "com.percona.pbm.app=mongod"
    environment:
      - REPLSET_NAME=rs2
      - MONGO_USER=dba
      - BACKUP_USER=bcp
      - MONGO_PASS=test1234
      - SINGLE_NODE=true
    command: mongod --replSet rs2 --port 27017 --storageEngine wiredTiger --keyFile /opt/keyFile --wiredTigerCacheSizeGB 1
    volumes:
      - data-rs201:/data/db
      - ./scripts/start.sh:/opt/start.sh

  agent-rs201:
    container_name: "pbmagent_rs201"
    user: "1001"
    labels:
      - "com.percona.pbm.app=agent"
      - "com.percona.pbm.agent.rs=rs2"
    environment:
      - "PBM_MONGODB_URI=mongodb://${BACKUP_USER:-bcp}:${MONGO_PASS:-test1234}@rs201:27017"
    build:
      labels:
        - "com.percona.pbm.app=agent"
      dockerfile: ./e2e-tests/docker/pbm.dockerfile
      context: ../..
      args:
        - MONGODB_VERSION=${MONGODB_VERSION:-5.0}
        - MONGODB_IMAGE=${MONGODB_IMAGE:-percona/percona-server-mongodb}
    volumes:
      - ./conf:/etc/pbm
      - ./backups:/opt/backups
      - data-rs201:/data/db
    command: pbm-agent
    cap_add:
      - NET_ADMIN

  minio:
    image: minio/minio:RELEASE.2022-08-08T18-34-09Z
    hostname: minio
    # ports:
    #   - "9000:9000"
    volumes:
      - backups:/backups
    environment:
      - "MINIO_ACCESS_KEY=minio1234"
      - "MINIO_SECRET_KEY=minio1234"
    command: server /backups
  createbucket:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c " sleep 5; /usr/bin/mc config host add myminio http://minio:9000 minio1234 minio1234; /usr/bin/mc mb myminio/bcp; exit 0; "
volumes:
  backups: null
  data-rs101: null
  data-rs201: null
