// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/api.proto

package apipb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BackupType int32

const (
	BackupType_BACKUP_TYPE_INVALID   BackupType = 0
	BackupType_BACKUP_TYPE_LOGICAL   BackupType = 1
	BackupType_BACKUP_TYPE_HOTBACKUP BackupType = 2
)

var BackupType_name = map[int32]string{
	0: "BACKUP_TYPE_INVALID",
	1: "BACKUP_TYPE_LOGICAL",
	2: "BACKUP_TYPE_HOTBACKUP",
}

var BackupType_value = map[string]int32{
	"BACKUP_TYPE_INVALID":   0,
	"BACKUP_TYPE_LOGICAL":   1,
	"BACKUP_TYPE_HOTBACKUP": 2,
}

func (x BackupType) String() string {
	return proto.EnumName(BackupType_name, int32(x))
}

func (BackupType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{0}
}

type DestinationType int32

const (
	DestinationType_DESTINATION_TYPE_INVALID DestinationType = 0
	DestinationType_DESTINATION_TYPE_FILE    DestinationType = 1
	DestinationType_DESTINATION_TYPE_AWS     DestinationType = 2
)

var DestinationType_name = map[int32]string{
	0: "DESTINATION_TYPE_INVALID",
	1: "DESTINATION_TYPE_FILE",
	2: "DESTINATION_TYPE_AWS",
}

var DestinationType_value = map[string]int32{
	"DESTINATION_TYPE_INVALID": 0,
	"DESTINATION_TYPE_FILE":    1,
	"DESTINATION_TYPE_AWS":     2,
}

func (x DestinationType) String() string {
	return proto.EnumName(DestinationType_name, int32(x))
}

func (DestinationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{1}
}

type CompressionType int32

const (
	CompressionType_COMPRESSION_TYPE_INVALID        CompressionType = 0
	CompressionType_COMPRESSION_TYPE_NO_COMPRESSION CompressionType = 1
	CompressionType_COMPRESSION_TYPE_GZIP           CompressionType = 2
	CompressionType_COMPRESSION_TYPE_SNAPPY         CompressionType = 3
	CompressionType_COMPRESSION_TYPE_LZ4            CompressionType = 4
)

var CompressionType_name = map[int32]string{
	0: "COMPRESSION_TYPE_INVALID",
	1: "COMPRESSION_TYPE_NO_COMPRESSION",
	2: "COMPRESSION_TYPE_GZIP",
	3: "COMPRESSION_TYPE_SNAPPY",
	4: "COMPRESSION_TYPE_LZ4",
}

var CompressionType_value = map[string]int32{
	"COMPRESSION_TYPE_INVALID":        0,
	"COMPRESSION_TYPE_NO_COMPRESSION": 1,
	"COMPRESSION_TYPE_GZIP":           2,
	"COMPRESSION_TYPE_SNAPPY":         3,
	"COMPRESSION_TYPE_LZ4":            4,
}

func (x CompressionType) String() string {
	return proto.EnumName(CompressionType_name, int32(x))
}

func (CompressionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{2}
}

type Cypher int32

const (
	Cypher_CYPHER_INVALID   Cypher = 0
	Cypher_CYPHER_NO_CYPHER Cypher = 1
	Cypher_CYPHER_AES       Cypher = 2
	Cypher_CYPHER_DES       Cypher = 3
	Cypher_CYPHER_RC4       Cypher = 4
	Cypher_CYPHER_RSA       Cypher = 5
)

var Cypher_name = map[int32]string{
	0: "CYPHER_INVALID",
	1: "CYPHER_NO_CYPHER",
	2: "CYPHER_AES",
	3: "CYPHER_DES",
	4: "CYPHER_RC4",
	5: "CYPHER_RSA",
}

var Cypher_value = map[string]int32{
	"CYPHER_INVALID":   0,
	"CYPHER_NO_CYPHER": 1,
	"CYPHER_AES":       2,
	"CYPHER_DES":       3,
	"CYPHER_RC4":       4,
	"CYPHER_RSA":       5,
}

func (x Cypher) String() string {
	return proto.EnumName(Cypher_name, int32(x))
}

func (Cypher) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{3}
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type BackupsMetadataParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackupsMetadataParams) Reset()         { *m = BackupsMetadataParams{} }
func (m *BackupsMetadataParams) String() string { return proto.CompactTextString(m) }
func (*BackupsMetadataParams) ProtoMessage()    {}
func (*BackupsMetadataParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{1}
}

func (m *BackupsMetadataParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupsMetadataParams.Unmarshal(m, b)
}
func (m *BackupsMetadataParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupsMetadataParams.Marshal(b, m, deterministic)
}
func (m *BackupsMetadataParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupsMetadataParams.Merge(m, src)
}
func (m *BackupsMetadataParams) XXX_Size() int {
	return xxx_messageInfo_BackupsMetadataParams.Size(m)
}
func (m *BackupsMetadataParams) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupsMetadataParams.DiscardUnknown(m)
}

var xxx_messageInfo_BackupsMetadataParams proto.InternalMessageInfo

type LastBackupMetadataParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LastBackupMetadataParams) Reset()         { *m = LastBackupMetadataParams{} }
func (m *LastBackupMetadataParams) String() string { return proto.CompactTextString(m) }
func (*LastBackupMetadataParams) ProtoMessage()    {}
func (*LastBackupMetadataParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{2}
}

func (m *LastBackupMetadataParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LastBackupMetadataParams.Unmarshal(m, b)
}
func (m *LastBackupMetadataParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LastBackupMetadataParams.Marshal(b, m, deterministic)
}
func (m *LastBackupMetadataParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LastBackupMetadataParams.Merge(m, src)
}
func (m *LastBackupMetadataParams) XXX_Size() int {
	return xxx_messageInfo_LastBackupMetadataParams.Size(m)
}
func (m *LastBackupMetadataParams) XXX_DiscardUnknown() {
	xxx_messageInfo_LastBackupMetadataParams.DiscardUnknown(m)
}

var xxx_messageInfo_LastBackupMetadataParams proto.InternalMessageInfo

type Error struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code                 int64    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{3}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

type ReplicasetMetadata struct {
	ClusterId            string   `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	ReplicasetUuid       string   `protobuf:"bytes,2,opt,name=replicaset_uuid,json=replicasetUuid,proto3" json:"replicaset_uuid,omitempty"`
	ReplicasetName       string   `protobuf:"bytes,3,opt,name=replicaset_name,json=replicasetName,proto3" json:"replicaset_name,omitempty"`
	DbBackupName         string   `protobuf:"bytes,4,opt,name=db_backup_name,json=dbBackupName,proto3" json:"db_backup_name,omitempty"`
	OplogBackupName      string   `protobuf:"bytes,5,opt,name=oplog_backup_name,json=oplogBackupName,proto3" json:"oplog_backup_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplicasetMetadata) Reset()         { *m = ReplicasetMetadata{} }
func (m *ReplicasetMetadata) String() string { return proto.CompactTextString(m) }
func (*ReplicasetMetadata) ProtoMessage()    {}
func (*ReplicasetMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{4}
}

func (m *ReplicasetMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicasetMetadata.Unmarshal(m, b)
}
func (m *ReplicasetMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicasetMetadata.Marshal(b, m, deterministic)
}
func (m *ReplicasetMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicasetMetadata.Merge(m, src)
}
func (m *ReplicasetMetadata) XXX_Size() int {
	return xxx_messageInfo_ReplicasetMetadata.Size(m)
}
func (m *ReplicasetMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicasetMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicasetMetadata proto.InternalMessageInfo

func (m *ReplicasetMetadata) GetClusterId() string {
	if m != nil {
		return m.ClusterId
	}
	return ""
}

func (m *ReplicasetMetadata) GetReplicasetUuid() string {
	if m != nil {
		return m.ReplicasetUuid
	}
	return ""
}

func (m *ReplicasetMetadata) GetReplicasetName() string {
	if m != nil {
		return m.ReplicasetName
	}
	return ""
}

func (m *ReplicasetMetadata) GetDbBackupName() string {
	if m != nil {
		return m.DbBackupName
	}
	return ""
}

func (m *ReplicasetMetadata) GetOplogBackupName() string {
	if m != nil {
		return m.OplogBackupName
	}
	return ""
}

type BackupMetadata struct {
	StartTs              int64                          `protobuf:"varint,1,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	EndTs                int64                          `protobuf:"varint,2,opt,name=end_ts,json=endTs,proto3" json:"end_ts,omitempty"`
	BackupType           BackupType                     `protobuf:"varint,3,opt,name=backup_type,json=backupType,proto3,enum=api.BackupType" json:"backup_type,omitempty"`
	OplogStartTime       int64                          `protobuf:"varint,4,opt,name=oplog_start_time,json=oplogStartTime,proto3" json:"oplog_start_time,omitempty"`
	LastOplogTs          int64                          `protobuf:"varint,5,opt,name=last_oplog_ts,json=lastOplogTs,proto3" json:"last_oplog_ts,omitempty"`
	DestinationType      DestinationType                `protobuf:"varint,6,opt,name=destination_type,json=destinationType,proto3,enum=api.DestinationType" json:"destination_type,omitempty"`
	DestinationDir       string                         `protobuf:"bytes,7,opt,name=destination_dir,json=destinationDir,proto3" json:"destination_dir,omitempty"`
	Cypher               Cypher                         `protobuf:"varint,8,opt,name=cypher,proto3,enum=api.Cypher" json:"cypher,omitempty"`
	CompressionType      CompressionType                `protobuf:"varint,9,opt,name=compression_type,json=compressionType,proto3,enum=api.CompressionType" json:"compression_type,omitempty"`
	Description          string                         `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	Replicasets          map[string]*ReplicasetMetadata `protobuf:"bytes,11,rep,name=replicasets,proto3" json:"replicasets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *BackupMetadata) Reset()         { *m = BackupMetadata{} }
func (m *BackupMetadata) String() string { return proto.CompactTextString(m) }
func (*BackupMetadata) ProtoMessage()    {}
func (*BackupMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{5}
}

func (m *BackupMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupMetadata.Unmarshal(m, b)
}
func (m *BackupMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupMetadata.Marshal(b, m, deterministic)
}
func (m *BackupMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupMetadata.Merge(m, src)
}
func (m *BackupMetadata) XXX_Size() int {
	return xxx_messageInfo_BackupMetadata.Size(m)
}
func (m *BackupMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_BackupMetadata proto.InternalMessageInfo

func (m *BackupMetadata) GetStartTs() int64 {
	if m != nil {
		return m.StartTs
	}
	return 0
}

func (m *BackupMetadata) GetEndTs() int64 {
	if m != nil {
		return m.EndTs
	}
	return 0
}

func (m *BackupMetadata) GetBackupType() BackupType {
	if m != nil {
		return m.BackupType
	}
	return BackupType_BACKUP_TYPE_INVALID
}

func (m *BackupMetadata) GetOplogStartTime() int64 {
	if m != nil {
		return m.OplogStartTime
	}
	return 0
}

func (m *BackupMetadata) GetLastOplogTs() int64 {
	if m != nil {
		return m.LastOplogTs
	}
	return 0
}

func (m *BackupMetadata) GetDestinationType() DestinationType {
	if m != nil {
		return m.DestinationType
	}
	return DestinationType_DESTINATION_TYPE_INVALID
}

func (m *BackupMetadata) GetDestinationDir() string {
	if m != nil {
		return m.DestinationDir
	}
	return ""
}

func (m *BackupMetadata) GetCypher() Cypher {
	if m != nil {
		return m.Cypher
	}
	return Cypher_CYPHER_INVALID
}

func (m *BackupMetadata) GetCompressionType() CompressionType {
	if m != nil {
		return m.CompressionType
	}
	return CompressionType_COMPRESSION_TYPE_INVALID
}

func (m *BackupMetadata) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *BackupMetadata) GetReplicasets() map[string]*ReplicasetMetadata {
	if m != nil {
		return m.Replicasets
	}
	return nil
}

type ClientStatus struct {
	ReplicasetUuid       string   `protobuf:"bytes,1,opt,name=replicaset_uuid,json=replicasetUuid,proto3" json:"replicaset_uuid,omitempty"`
	ReplicasetName       string   `protobuf:"bytes,2,opt,name=replicaset_name,json=replicasetName,proto3" json:"replicaset_name,omitempty"`
	ReplicasetVersion    uint64   `protobuf:"varint,3,opt,name=replicaset_version,json=replicasetVersion,proto3" json:"replicaset_version,omitempty"`
	RunningDbBackup      bool     `protobuf:"varint,4,opt,name=running_db_backup,json=runningDbBackup,proto3" json:"running_db_backup,omitempty"`
	RunningOplogBackup   bool     `protobuf:"varint,5,opt,name=running_oplog_backup,json=runningOplogBackup,proto3" json:"running_oplog_backup,omitempty"`
	BackupType           string   `protobuf:"bytes,6,opt,name=backup_type,json=backupType,proto3" json:"backup_type,omitempty"`
	Compression          string   `protobuf:"bytes,7,opt,name=compression,proto3" json:"compression,omitempty"`
	Encrypted            string   `protobuf:"bytes,8,opt,name=encrypted,proto3" json:"encrypted,omitempty"`
	Destination          string   `protobuf:"bytes,9,opt,name=destination,proto3" json:"destination,omitempty"`
	Dirname              string   `protobuf:"bytes,10,opt,name=dirname,proto3" json:"dirname,omitempty"`
	Filename             string   `protobuf:"bytes,11,opt,name=filename,proto3" json:"filename,omitempty"`
	Started              int64    `protobuf:"varint,12,opt,name=started,proto3" json:"started,omitempty"`
	Finished             int64    `protobuf:"varint,13,opt,name=finished,proto3" json:"finished,omitempty"`
	StartOplogTs         int64    `protobuf:"varint,14,opt,name=start_oplog_ts,json=startOplogTs,proto3" json:"start_oplog_ts,omitempty"`
	LastOplogTs          int64    `protobuf:"varint,15,opt,name=last_oplog_ts,json=lastOplogTs,proto3" json:"last_oplog_ts,omitempty"`
	LastError            string   `protobuf:"bytes,16,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientStatus) Reset()         { *m = ClientStatus{} }
func (m *ClientStatus) String() string { return proto.CompactTextString(m) }
func (*ClientStatus) ProtoMessage()    {}
func (*ClientStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{6}
}

func (m *ClientStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientStatus.Unmarshal(m, b)
}
func (m *ClientStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientStatus.Marshal(b, m, deterministic)
}
func (m *ClientStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientStatus.Merge(m, src)
}
func (m *ClientStatus) XXX_Size() int {
	return xxx_messageInfo_ClientStatus.Size(m)
}
func (m *ClientStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ClientStatus proto.InternalMessageInfo

func (m *ClientStatus) GetReplicasetUuid() string {
	if m != nil {
		return m.ReplicasetUuid
	}
	return ""
}

func (m *ClientStatus) GetReplicasetName() string {
	if m != nil {
		return m.ReplicasetName
	}
	return ""
}

func (m *ClientStatus) GetReplicasetVersion() uint64 {
	if m != nil {
		return m.ReplicasetVersion
	}
	return 0
}

func (m *ClientStatus) GetRunningDbBackup() bool {
	if m != nil {
		return m.RunningDbBackup
	}
	return false
}

func (m *ClientStatus) GetRunningOplogBackup() bool {
	if m != nil {
		return m.RunningOplogBackup
	}
	return false
}

func (m *ClientStatus) GetBackupType() string {
	if m != nil {
		return m.BackupType
	}
	return ""
}

func (m *ClientStatus) GetCompression() string {
	if m != nil {
		return m.Compression
	}
	return ""
}

func (m *ClientStatus) GetEncrypted() string {
	if m != nil {
		return m.Encrypted
	}
	return ""
}

func (m *ClientStatus) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *ClientStatus) GetDirname() string {
	if m != nil {
		return m.Dirname
	}
	return ""
}

func (m *ClientStatus) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *ClientStatus) GetStarted() int64 {
	if m != nil {
		return m.Started
	}
	return 0
}

func (m *ClientStatus) GetFinished() int64 {
	if m != nil {
		return m.Finished
	}
	return 0
}

func (m *ClientStatus) GetStartOplogTs() int64 {
	if m != nil {
		return m.StartOplogTs
	}
	return 0
}

func (m *ClientStatus) GetLastOplogTs() int64 {
	if m != nil {
		return m.LastOplogTs
	}
	return 0
}

func (m *ClientStatus) GetLastError() string {
	if m != nil {
		return m.LastError
	}
	return ""
}

type Client struct {
	Version              int32         `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Id                   string        `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	NodeType             string        `protobuf:"bytes,3,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	NodeName             string        `protobuf:"bytes,4,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	ClusterId            string        `protobuf:"bytes,5,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	ReplicasetName       string        `protobuf:"bytes,6,opt,name=replicaset_name,json=replicasetName,proto3" json:"replicaset_name,omitempty"`
	ReplicasetId         string        `protobuf:"bytes,7,opt,name=replicaset_id,json=replicasetId,proto3" json:"replicaset_id,omitempty"`
	LastCommandSent      string        `protobuf:"bytes,8,opt,name=last_command_sent,json=lastCommandSent,proto3" json:"last_command_sent,omitempty"`
	LastSeen             int64         `protobuf:"varint,9,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	Status               *ClientStatus `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Client) Reset()         { *m = Client{} }
func (m *Client) String() string { return proto.CompactTextString(m) }
func (*Client) ProtoMessage()    {}
func (*Client) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{7}
}

func (m *Client) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Client.Unmarshal(m, b)
}
func (m *Client) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Client.Marshal(b, m, deterministic)
}
func (m *Client) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Client.Merge(m, src)
}
func (m *Client) XXX_Size() int {
	return xxx_messageInfo_Client.Size(m)
}
func (m *Client) XXX_DiscardUnknown() {
	xxx_messageInfo_Client.DiscardUnknown(m)
}

var xxx_messageInfo_Client proto.InternalMessageInfo

func (m *Client) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Client) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Client) GetNodeType() string {
	if m != nil {
		return m.NodeType
	}
	return ""
}

func (m *Client) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *Client) GetClusterId() string {
	if m != nil {
		return m.ClusterId
	}
	return ""
}

func (m *Client) GetReplicasetName() string {
	if m != nil {
		return m.ReplicasetName
	}
	return ""
}

func (m *Client) GetReplicasetId() string {
	if m != nil {
		return m.ReplicasetId
	}
	return ""
}

func (m *Client) GetLastCommandSent() string {
	if m != nil {
		return m.LastCommandSent
	}
	return ""
}

func (m *Client) GetLastSeen() int64 {
	if m != nil {
		return m.LastSeen
	}
	return 0
}

func (m *Client) GetStatus() *ClientStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type MetadataFile struct {
	Filename             string          `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Metadata             *BackupMetadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MetadataFile) Reset()         { *m = MetadataFile{} }
func (m *MetadataFile) String() string { return proto.CompactTextString(m) }
func (*MetadataFile) ProtoMessage()    {}
func (*MetadataFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{8}
}

func (m *MetadataFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetadataFile.Unmarshal(m, b)
}
func (m *MetadataFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetadataFile.Marshal(b, m, deterministic)
}
func (m *MetadataFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetadataFile.Merge(m, src)
}
func (m *MetadataFile) XXX_Size() int {
	return xxx_messageInfo_MetadataFile.Size(m)
}
func (m *MetadataFile) XXX_DiscardUnknown() {
	xxx_messageInfo_MetadataFile.DiscardUnknown(m)
}

var xxx_messageInfo_MetadataFile proto.InternalMessageInfo

func (m *MetadataFile) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *MetadataFile) GetMetadata() *BackupMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type RunBackupParams struct {
	BackupType           BackupType      `protobuf:"varint,1,opt,name=backup_type,json=backupType,proto3,enum=api.BackupType" json:"backup_type,omitempty"`
	CompressionType      CompressionType `protobuf:"varint,2,opt,name=compression_type,json=compressionType,proto3,enum=api.CompressionType" json:"compression_type,omitempty"`
	Cypher               Cypher          `protobuf:"varint,3,opt,name=cypher,proto3,enum=api.Cypher" json:"cypher,omitempty"`
	DestinationType      DestinationType `protobuf:"varint,4,opt,name=destination_type,json=destinationType,proto3,enum=api.DestinationType" json:"destination_type,omitempty"`
	Dirname              string          `protobuf:"bytes,5,opt,name=dirname,proto3" json:"dirname,omitempty"`
	Filename             string          `protobuf:"bytes,6,opt,name=filename,proto3" json:"filename,omitempty"`
	StartOplogTs         int64           `protobuf:"varint,7,opt,name=start_oplog_ts,json=startOplogTs,proto3" json:"start_oplog_ts,omitempty"`
	Description          string          `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RunBackupParams) Reset()         { *m = RunBackupParams{} }
func (m *RunBackupParams) String() string { return proto.CompactTextString(m) }
func (*RunBackupParams) ProtoMessage()    {}
func (*RunBackupParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{9}
}

func (m *RunBackupParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunBackupParams.Unmarshal(m, b)
}
func (m *RunBackupParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunBackupParams.Marshal(b, m, deterministic)
}
func (m *RunBackupParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunBackupParams.Merge(m, src)
}
func (m *RunBackupParams) XXX_Size() int {
	return xxx_messageInfo_RunBackupParams.Size(m)
}
func (m *RunBackupParams) XXX_DiscardUnknown() {
	xxx_messageInfo_RunBackupParams.DiscardUnknown(m)
}

var xxx_messageInfo_RunBackupParams proto.InternalMessageInfo

func (m *RunBackupParams) GetBackupType() BackupType {
	if m != nil {
		return m.BackupType
	}
	return BackupType_BACKUP_TYPE_INVALID
}

func (m *RunBackupParams) GetCompressionType() CompressionType {
	if m != nil {
		return m.CompressionType
	}
	return CompressionType_COMPRESSION_TYPE_INVALID
}

func (m *RunBackupParams) GetCypher() Cypher {
	if m != nil {
		return m.Cypher
	}
	return Cypher_CYPHER_INVALID
}

func (m *RunBackupParams) GetDestinationType() DestinationType {
	if m != nil {
		return m.DestinationType
	}
	return DestinationType_DESTINATION_TYPE_INVALID
}

func (m *RunBackupParams) GetDirname() string {
	if m != nil {
		return m.Dirname
	}
	return ""
}

func (m *RunBackupParams) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *RunBackupParams) GetStartOplogTs() int64 {
	if m != nil {
		return m.StartOplogTs
	}
	return 0
}

func (m *RunBackupParams) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type RunRestoreParams struct {
	MetadataFile         string   `protobuf:"bytes,1,opt,name=metadata_file,json=metadataFile,proto3" json:"metadata_file,omitempty"`
	SkipUsersAndRoles    bool     `protobuf:"varint,2,opt,name=skip_users_and_roles,json=skipUsersAndRoles,proto3" json:"skip_users_and_roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunRestoreParams) Reset()         { *m = RunRestoreParams{} }
func (m *RunRestoreParams) String() string { return proto.CompactTextString(m) }
func (*RunRestoreParams) ProtoMessage()    {}
func (*RunRestoreParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{10}
}

func (m *RunRestoreParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunRestoreParams.Unmarshal(m, b)
}
func (m *RunRestoreParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunRestoreParams.Marshal(b, m, deterministic)
}
func (m *RunRestoreParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunRestoreParams.Merge(m, src)
}
func (m *RunRestoreParams) XXX_Size() int {
	return xxx_messageInfo_RunRestoreParams.Size(m)
}
func (m *RunRestoreParams) XXX_DiscardUnknown() {
	xxx_messageInfo_RunRestoreParams.DiscardUnknown(m)
}

var xxx_messageInfo_RunRestoreParams proto.InternalMessageInfo

func (m *RunRestoreParams) GetMetadataFile() string {
	if m != nil {
		return m.MetadataFile
	}
	return ""
}

func (m *RunRestoreParams) GetSkipUsersAndRoles() bool {
	if m != nil {
		return m.SkipUsersAndRoles
	}
	return false
}

type RunRestoreResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunRestoreResponse) Reset()         { *m = RunRestoreResponse{} }
func (m *RunRestoreResponse) String() string { return proto.CompactTextString(m) }
func (*RunRestoreResponse) ProtoMessage()    {}
func (*RunRestoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{11}
}

func (m *RunRestoreResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunRestoreResponse.Unmarshal(m, b)
}
func (m *RunRestoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunRestoreResponse.Marshal(b, m, deterministic)
}
func (m *RunRestoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunRestoreResponse.Merge(m, src)
}
func (m *RunRestoreResponse) XXX_Size() int {
	return xxx_messageInfo_RunRestoreResponse.Size(m)
}
func (m *RunRestoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RunRestoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RunRestoreResponse proto.InternalMessageInfo

func (m *RunRestoreResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type BackupReplica struct {
	AgentId              string   `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	NodeType             string   `protobuf:"bytes,2,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	NodeName             string   `protobuf:"bytes,3,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	ClusterId            string   `protobuf:"bytes,4,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	ReplicasetName       string   `protobuf:"bytes,5,opt,name=replicaset_name,json=replicasetName,proto3" json:"replicaset_name,omitempty"`
	ReplicasetId         string   `protobuf:"bytes,6,opt,name=replicaset_id,json=replicasetId,proto3" json:"replicaset_id,omitempty"`
	StartedAt            int64    `protobuf:"varint,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackupReplica) Reset()         { *m = BackupReplica{} }
func (m *BackupReplica) String() string { return proto.CompactTextString(m) }
func (*BackupReplica) ProtoMessage()    {}
func (*BackupReplica) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{12}
}

func (m *BackupReplica) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupReplica.Unmarshal(m, b)
}
func (m *BackupReplica) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupReplica.Marshal(b, m, deterministic)
}
func (m *BackupReplica) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupReplica.Merge(m, src)
}
func (m *BackupReplica) XXX_Size() int {
	return xxx_messageInfo_BackupReplica.Size(m)
}
func (m *BackupReplica) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupReplica.DiscardUnknown(m)
}

var xxx_messageInfo_BackupReplica proto.InternalMessageInfo

func (m *BackupReplica) GetAgentId() string {
	if m != nil {
		return m.AgentId
	}
	return ""
}

func (m *BackupReplica) GetNodeType() string {
	if m != nil {
		return m.NodeType
	}
	return ""
}

func (m *BackupReplica) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *BackupReplica) GetClusterId() string {
	if m != nil {
		return m.ClusterId
	}
	return ""
}

func (m *BackupReplica) GetReplicasetName() string {
	if m != nil {
		return m.ReplicasetName
	}
	return ""
}

func (m *BackupReplica) GetReplicasetId() string {
	if m != nil {
		return m.ReplicasetId
	}
	return ""
}

func (m *BackupReplica) GetStartedAt() int64 {
	if m != nil {
		return m.StartedAt
	}
	return 0
}

func init() {
	proto.RegisterEnum("api.BackupType", BackupType_name, BackupType_value)
	proto.RegisterEnum("api.DestinationType", DestinationType_name, DestinationType_value)
	proto.RegisterEnum("api.CompressionType", CompressionType_name, CompressionType_value)
	proto.RegisterEnum("api.Cypher", Cypher_name, Cypher_value)
	proto.RegisterType((*Empty)(nil), "api.Empty")
	proto.RegisterType((*BackupsMetadataParams)(nil), "api.BackupsMetadataParams")
	proto.RegisterType((*LastBackupMetadataParams)(nil), "api.LastBackupMetadataParams")
	proto.RegisterType((*Error)(nil), "api.Error")
	proto.RegisterType((*ReplicasetMetadata)(nil), "api.ReplicasetMetadata")
	proto.RegisterType((*BackupMetadata)(nil), "api.BackupMetadata")
	proto.RegisterMapType((map[string]*ReplicasetMetadata)(nil), "api.BackupMetadata.ReplicasetsEntry")
	proto.RegisterType((*ClientStatus)(nil), "api.ClientStatus")
	proto.RegisterType((*Client)(nil), "api.Client")
	proto.RegisterType((*MetadataFile)(nil), "api.MetadataFile")
	proto.RegisterType((*RunBackupParams)(nil), "api.RunBackupParams")
	proto.RegisterType((*RunRestoreParams)(nil), "api.RunRestoreParams")
	proto.RegisterType((*RunRestoreResponse)(nil), "api.RunRestoreResponse")
	proto.RegisterType((*BackupReplica)(nil), "api.BackupReplica")
}

func init() { proto.RegisterFile("api/api.proto", fileDescriptor_1b40cafcd4234784) }

var fileDescriptor_1b40cafcd4234784 = []byte{
	// 1390 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x57, 0xdd, 0x6e, 0xdb, 0x46,
	0x13, 0x35, 0x49, 0xfd, 0x8e, 0x64, 0x89, 0xde, 0xd8, 0x30, 0xa3, 0xc4, 0x88, 0x41, 0x07, 0xf8,
	0x1c, 0x03, 0x89, 0x03, 0x7f, 0x29, 0x50, 0xf4, 0xa2, 0x85, 0x2c, 0x29, 0x89, 0x5a, 0xc7, 0x12,
	0x56, 0x4a, 0x02, 0xa7, 0x17, 0x04, 0x2d, 0x6e, 0x1d, 0x22, 0x12, 0x49, 0x70, 0xa9, 0x00, 0x7a,
	0xa1, 0xbe, 0x40, 0x9f, 0xa1, 0x97, 0xbd, 0x2c, 0xfa, 0x0a, 0xbd, 0xec, 0x23, 0x14, 0xfb, 0x43,
	0x71, 0x45, 0x29, 0xae, 0x73, 0xc7, 0x99, 0x33, 0xbb, 0x3b, 0xbb, 0x73, 0xce, 0x2c, 0x17, 0xb6,
	0xdd, 0xc8, 0x3f, 0x75, 0x23, 0xff, 0x59, 0x14, 0x87, 0x49, 0x88, 0x0c, 0x37, 0xf2, 0xed, 0x32,
	0x14, 0x7b, 0xb3, 0x28, 0x59, 0xd8, 0xfb, 0xb0, 0x77, 0xee, 0x4e, 0x3e, 0xcd, 0x23, 0xfa, 0x86,
	0x24, 0xae, 0xe7, 0x26, 0xee, 0xd0, 0x8d, 0xdd, 0x19, 0xb5, 0x5b, 0x60, 0x5d, 0xb8, 0x34, 0x11,
	0x60, 0x0e, 0xfb, 0x06, 0x8a, 0xbd, 0x38, 0x0e, 0x63, 0x64, 0x41, 0x79, 0x46, 0x28, 0x75, 0x6f,
	0x88, 0xa5, 0x1d, 0x6a, 0xc7, 0x55, 0x9c, 0x9a, 0x08, 0x41, 0x61, 0x12, 0x7a, 0xc4, 0xd2, 0x0f,
	0xb5, 0x63, 0x03, 0xf3, 0x6f, 0xfb, 0x2f, 0x0d, 0x10, 0x26, 0xd1, 0xd4, 0x9f, 0xb8, 0x94, 0x24,
	0xe9, 0x9c, 0xe8, 0x00, 0x60, 0x32, 0x9d, 0xd3, 0x84, 0xc4, 0x8e, 0xef, 0xc9, 0x79, 0xaa, 0xd2,
	0xd3, 0xf7, 0xd0, 0xff, 0xa0, 0x19, 0x2f, 0x07, 0x39, 0xf3, 0xb9, 0xef, 0xf1, 0x49, 0xab, 0xb8,
	0x91, 0xb9, 0xdf, 0xce, 0xfd, 0x7c, 0x60, 0xe0, 0xce, 0x88, 0x65, 0xe4, 0x03, 0x2f, 0xdd, 0x19,
	0x41, 0x8f, 0xa1, 0xe1, 0x5d, 0x3b, 0xd7, 0x7c, 0x67, 0x22, 0xae, 0xc0, 0xe3, 0xea, 0xde, 0xb5,
	0xd8, 0x2e, 0x8f, 0x3a, 0x81, 0x9d, 0x30, 0x9a, 0x86, 0x37, 0x2b, 0x81, 0x45, 0x1e, 0xd8, 0xe4,
	0x40, 0x16, 0x6b, 0xff, 0x59, 0x80, 0xc6, 0xea, 0x49, 0xa1, 0xfb, 0x50, 0xa1, 0x89, 0x1b, 0x27,
	0x4e, 0x42, 0xf9, 0x9e, 0x0c, 0x5c, 0xe6, 0xf6, 0x98, 0xa2, 0x3d, 0x28, 0x91, 0xc0, 0x63, 0x80,
	0x38, 0x9d, 0x22, 0x09, 0xbc, 0x31, 0x45, 0xcf, 0xa1, 0x26, 0x97, 0x4a, 0x16, 0x91, 0xc8, 0xbd,
	0x71, 0xd6, 0x7c, 0xc6, 0x2a, 0x27, 0xe6, 0x1e, 0x2f, 0x22, 0x82, 0xe1, 0x7a, 0xf9, 0x8d, 0x8e,
	0xc1, 0x14, 0x29, 0xca, 0x95, 0x7c, 0xb9, 0x15, 0x03, 0x37, 0xb8, 0x7f, 0xc4, 0x17, 0xf4, 0x67,
	0x04, 0xd9, 0xb0, 0x3d, 0x75, 0x69, 0xe2, 0x88, 0xf0, 0x84, 0xf2, 0x8d, 0x18, 0xb8, 0xc6, 0x9c,
	0x03, 0xe6, 0x1b, 0x53, 0xf4, 0x03, 0x98, 0x1e, 0xa1, 0x89, 0x1f, 0xb8, 0x89, 0x1f, 0x06, 0x22,
	0x89, 0x12, 0x4f, 0x62, 0x97, 0x27, 0xd1, 0xcd, 0x40, 0x9e, 0x49, 0xd3, 0x5b, 0x75, 0xb0, 0x02,
	0xa8, 0x13, 0x78, 0x7e, 0x6c, 0x95, 0x45, 0x01, 0x14, 0x77, 0xd7, 0x8f, 0xd1, 0x11, 0x94, 0x26,
	0x8b, 0xe8, 0x23, 0x89, 0xad, 0x0a, 0x9f, 0xbf, 0xc6, 0xe7, 0xef, 0x70, 0x17, 0x96, 0x10, 0x4b,
	0x67, 0x12, 0xce, 0xa2, 0x98, 0x50, 0xba, 0x4c, 0xa7, 0xaa, 0xa4, 0xd3, 0xc9, 0x40, 0x91, 0xce,
	0x64, 0xd5, 0x81, 0x0e, 0xa1, 0xe6, 0x11, 0x3a, 0x89, 0xfd, 0x88, 0xad, 0x6b, 0x01, 0x4f, 0x45,
	0x75, 0xa1, 0x97, 0x50, 0xcb, 0xa8, 0x41, 0xad, 0xda, 0xa1, 0x71, 0x5c, 0x3b, 0x7b, 0xac, 0x9c,
	0x78, 0x5a, 0xcd, 0x67, 0x19, 0x6d, 0x69, 0x2f, 0x48, 0xe2, 0x05, 0x56, 0x07, 0xb6, 0xde, 0x83,
	0x99, 0x0f, 0x40, 0x26, 0x18, 0x9f, 0xc8, 0x42, 0xd2, 0x99, 0x7d, 0xa2, 0xa7, 0x50, 0xfc, 0xec,
	0x4e, 0xe7, 0x42, 0x13, 0xb5, 0xb3, 0x7d, 0xbe, 0xce, 0xba, 0x1e, 0xb0, 0x88, 0xfa, 0x4e, 0xff,
	0x56, 0xb3, 0x7f, 0x2f, 0x40, 0xbd, 0x33, 0xf5, 0x49, 0x90, 0x8c, 0x12, 0x37, 0x99, 0xd3, 0x4d,
	0x62, 0xd0, 0xee, 0x2a, 0x06, 0x7d, 0xa3, 0x18, 0x9e, 0x02, 0x52, 0x02, 0x3f, 0x93, 0x98, 0x9d,
	0x1f, 0x27, 0x5f, 0x01, 0xef, 0x64, 0xc8, 0x3b, 0x01, 0x30, 0x55, 0xc4, 0xf3, 0x20, 0xf0, 0x83,
	0x1b, 0x67, 0xa9, 0x21, 0xce, 0xb9, 0x0a, 0x6e, 0x4a, 0xa0, 0x2b, 0x55, 0x84, 0x9e, 0xc3, 0x6e,
	0x1a, 0xab, 0x2a, 0x89, 0x73, 0xaf, 0x82, 0x91, 0xc4, 0x06, 0x99, 0x96, 0xd0, 0xa3, 0x55, 0x09,
	0x94, 0x78, 0xc6, 0x2a, 0xe3, 0x0f, 0xa1, 0xa6, 0x94, 0x59, 0xd2, 0x4b, 0x75, 0xa1, 0x87, 0x50,
	0x25, 0xc1, 0x24, 0x5e, 0x44, 0x09, 0xf1, 0x38, 0xbd, 0xaa, 0x38, 0x73, 0x48, 0x4e, 0xa4, 0x5c,
	0xe4, 0x7c, 0x12, 0x9c, 0x48, 0x5d, 0xac, 0xa5, 0x79, 0x7e, 0xcc, 0x0f, 0x4c, 0x30, 0x26, 0x35,
	0x51, 0x0b, 0x2a, 0xbf, 0xf8, 0x53, 0xc2, 0xa1, 0x1a, 0x87, 0x96, 0x36, 0x1b, 0xc5, 0x35, 0x48,
	0x3c, 0xab, 0xae, 0x88, 0x9d, 0x78, 0x62, 0x54, 0xe0, 0xd3, 0x8f, 0xc4, 0xb3, 0xb6, 0x39, 0xb4,
	0xb4, 0x59, 0x23, 0x12, 0xca, 0x5d, 0xca, 0xb2, 0xc1, 0x23, 0xea, 0xdc, 0x9b, 0xea, 0x72, 0x4d,
	0xbb, 0xcd, 0x75, 0xed, 0x1e, 0x00, 0xf0, 0x18, 0xc2, 0xda, 0xb2, 0x65, 0x8a, 0x6d, 0x33, 0x0f,
	0xef, 0xd3, 0xf6, 0x1f, 0x3a, 0x94, 0x04, 0x8f, 0x58, 0xa6, 0x69, 0x91, 0x19, 0x73, 0x8a, 0x38,
	0x35, 0x51, 0x03, 0xf4, 0x65, 0x6f, 0xd5, 0x7d, 0x0f, 0x3d, 0x80, 0x6a, 0x10, 0x7a, 0x24, 0xeb,
	0x46, 0x55, 0x5c, 0x61, 0x0e, 0x5e, 0x88, 0x14, 0x54, 0xda, 0x27, 0x07, 0x39, 0xa7, 0x56, 0x3b,
	0x7a, 0xf1, 0xf6, 0x8e, 0xce, 0x67, 0x28, 0x6d, 0xe4, 0xe6, 0x11, 0x6c, 0x2b, 0x81, 0xbe, 0x27,
	0xeb, 0x5d, 0xcf, 0x9c, 0x7d, 0x8f, 0x31, 0x92, 0x6f, 0x7d, 0x12, 0xce, 0x66, 0x6e, 0xe0, 0x39,
	0x94, 0x04, 0x89, 0x2c, 0x7c, 0x93, 0x01, 0x1d, 0xe1, 0x1f, 0xb1, 0xcd, 0x3f, 0x00, 0x7e, 0x28,
	0x0e, 0x25, 0x44, 0x14, 0xdf, 0xc0, 0x15, 0xe6, 0x18, 0x11, 0x12, 0xa0, 0x27, 0x50, 0xa2, 0x5c,
	0x65, 0xbc, 0xf0, 0xb5, 0xb3, 0x1d, 0xd1, 0x66, 0x14, 0xf9, 0x61, 0x19, 0x60, 0xff, 0x0c, 0xf5,
	0x54, 0xae, 0x2f, 0xfd, 0xe9, 0x2a, 0x35, 0xb4, 0x1c, 0x35, 0x4e, 0xa1, 0x32, 0x93, 0xb1, 0x52,
	0xf9, 0xf7, 0x36, 0x74, 0x18, 0xbc, 0x0c, 0xb2, 0xff, 0xd6, 0xa1, 0x89, 0xe7, 0x81, 0xc0, 0xc5,
	0x8d, 0x9b, 0xbf, 0x1b, 0xb4, 0xff, 0xbe, 0x1b, 0x36, 0xb5, 0x4f, 0xfd, 0x6b, 0xda, 0x67, 0xd6,
	0xa4, 0x8d, 0x5b, 0x9b, 0xf4, 0xda, 0x9d, 0x51, 0xf8, 0x9a, 0x3b, 0x43, 0x91, 0x5b, 0xf1, 0xcb,
	0x72, 0x2b, 0xe5, 0xce, 0x74, 0x5d, 0x38, 0xe5, 0x0d, 0xc2, 0xc9, 0x5d, 0x00, 0x95, 0xb5, 0x0b,
	0xc0, 0xfe, 0x08, 0x26, 0x9e, 0x07, 0x98, 0xd0, 0x24, 0x8c, 0x89, 0x3c, 0xea, 0x23, 0xd8, 0x4e,
	0x4b, 0xe1, 0xb0, 0x05, 0x65, 0x41, 0xeb, 0x33, 0xb5, 0xe0, 0xa7, 0xb0, 0x4b, 0x3f, 0xf9, 0x91,
	0x33, 0xa7, 0x24, 0xa6, 0x0e, 0xa3, 0x5d, 0x1c, 0x4e, 0x89, 0xb8, 0xd0, 0x2b, 0x78, 0x87, 0x61,
	0x6f, 0x19, 0xd4, 0x0e, 0x3c, 0xcc, 0x00, 0xfb, 0x04, 0x50, 0xb6, 0x12, 0x26, 0x34, 0x0a, 0x03,
	0x4a, 0xd0, 0x2e, 0x14, 0x85, 0x62, 0xc5, 0x1a, 0xc2, 0xb0, 0xff, 0xd1, 0x60, 0x5b, 0x54, 0x55,
	0xde, 0x0e, 0xec, 0x67, 0xc2, 0xbd, 0x21, 0x41, 0x92, 0xfd, 0x20, 0x95, 0xb9, 0xdd, 0xcf, 0xa9,
	0x54, 0xbf, 0x4d, 0xa5, 0xc6, 0xad, 0x2a, 0x2d, 0xdc, 0x41, 0xa5, 0xc5, 0xbb, 0xa9, 0xb4, 0xb4,
	0x41, 0xa5, 0x07, 0x00, 0xb2, 0x23, 0x3a, 0x6e, 0x22, 0xab, 0x55, 0x95, 0x9e, 0x76, 0x72, 0x72,
	0x05, 0x90, 0xf1, 0x18, 0xed, 0xc3, 0xbd, 0xf3, 0x76, 0xe7, 0xa7, 0xb7, 0x43, 0x67, 0x7c, 0x35,
	0xec, 0x39, 0xfd, 0xcb, 0x77, 0xed, 0x8b, 0x7e, 0xd7, 0xdc, 0xca, 0x03, 0x17, 0x83, 0x57, 0xfd,
	0x4e, 0xfb, 0xc2, 0xd4, 0xd0, 0x7d, 0xd8, 0x53, 0x81, 0xd7, 0x83, 0xb1, 0x30, 0x4d, 0xfd, 0xc4,
	0x83, 0x66, 0x8e, 0x85, 0xe8, 0x21, 0x58, 0xdd, 0xde, 0x68, 0xdc, 0xbf, 0x6c, 0x8f, 0xfb, 0x83,
	0xcb, 0xfc, 0x22, 0xf7, 0x61, 0x6f, 0x0d, 0x7d, 0xd9, 0xbf, 0xe8, 0x99, 0x1a, 0xb2, 0x60, 0x77,
	0x0d, 0x6a, 0xbf, 0x1f, 0x99, 0xfa, 0xc9, 0xaf, 0x1a, 0x34, 0x73, 0x92, 0x62, 0xcb, 0x74, 0x06,
	0x6f, 0x86, 0xb8, 0x37, 0x1a, 0x6d, 0x58, 0xe6, 0x08, 0x1e, 0xad, 0xa1, 0x97, 0x03, 0x47, 0xf1,
	0x89, 0x7d, 0xad, 0x05, 0xbd, 0xfa, 0xd0, 0x1f, 0x9a, 0x3a, 0x7a, 0x00, 0xfb, 0x6b, 0xd0, 0xe8,
	0xb2, 0x3d, 0x1c, 0x5e, 0x99, 0x06, 0x4b, 0x74, 0x0d, 0xbc, 0xf8, 0xf0, 0xc2, 0x2c, 0x9c, 0xc4,
	0x50, 0x12, 0x1a, 0x46, 0x08, 0x1a, 0x9d, 0xab, 0xe1, 0xeb, 0x1e, 0x56, 0x92, 0xda, 0x05, 0x53,
	0xfa, 0x58, 0x2a, 0xfc, 0xcb, 0xd4, 0x50, 0x03, 0x40, 0x7a, 0xdb, 0xbd, 0x91, 0xa9, 0x2b, 0x76,
	0xb7, 0x37, 0x32, 0x0d, 0xc5, 0xc6, 0x9d, 0x17, 0x66, 0x41, 0xb5, 0x47, 0x6d, 0xb3, 0x78, 0xf6,
	0x9b, 0x0e, 0x46, 0x3b, 0xf2, 0xd1, 0x13, 0x80, 0x57, 0x24, 0x11, 0x1d, 0x95, 0x22, 0xe0, 0x1d,
	0x82, 0x3f, 0x43, 0x5a, 0x35, 0xa5, 0xd7, 0xda, 0x5b, 0xcf, 0x35, 0x74, 0x0a, 0xd5, 0x65, 0x0f,
	0x44, 0xa2, 0x97, 0xe4, 0x7a, 0x62, 0x4b, 0x8e, 0xe7, 0x92, 0xd9, 0x42, 0xdf, 0x03, 0x64, 0x02,
	0x43, 0x7b, 0xe9, 0x88, 0x15, 0x6d, 0xb7, 0xf6, 0x73, 0xee, 0x54, 0x88, 0xf6, 0x16, 0xfa, 0x11,
	0xd0, 0xfa, 0x7b, 0x07, 0x1d, 0xf0, 0x01, 0x5f, 0x7a, 0x08, 0xb5, 0x36, 0x75, 0x72, 0x7b, 0x0b,
	0x75, 0xa1, 0x99, 0x7b, 0x54, 0xa1, 0x96, 0x12, 0x99, 0x7b, 0x6a, 0xb5, 0xc4, 0x45, 0xa3, 0x5e,
	0x28, 0xec, 0x08, 0xce, 0x1f, 0x42, 0x79, 0x12, 0xce, 0x18, 0x76, 0x5e, 0x69, 0x47, 0xfe, 0x90,
	0xbd, 0xde, 0x86, 0xda, 0x87, 0xa2, 0x1b, 0xf9, 0xd1, 0xf5, 0x75, 0x89, 0xbf, 0xe6, 0xfe, 0xff,
	0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3b, 0xc7, 0x6d, 0x27, 0xde, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ApiClient is the client API for Api service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ApiClient interface {
	GetClients(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Api_GetClientsClient, error)
	RunBackup(ctx context.Context, in *RunBackupParams, opts ...grpc.CallOption) (*Error, error)
	RunRestore(ctx context.Context, in *RunRestoreParams, opts ...grpc.CallOption) (*RunRestoreResponse, error)
	LastBackupMetadata(ctx context.Context, in *LastBackupMetadataParams, opts ...grpc.CallOption) (*BackupMetadata, error)
	BackupsMetadata(ctx context.Context, in *BackupsMetadataParams, opts ...grpc.CallOption) (Api_BackupsMetadataClient, error)
}

type apiClient struct {
	cc *grpc.ClientConn
}

func NewApiClient(cc *grpc.ClientConn) ApiClient {
	return &apiClient{cc}
}

func (c *apiClient) GetClients(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Api_GetClientsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Api_serviceDesc.Streams[0], "/api.Api/GetClients", opts...)
	if err != nil {
		return nil, err
	}
	x := &apiGetClientsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Api_GetClientsClient interface {
	Recv() (*Client, error)
	grpc.ClientStream
}

type apiGetClientsClient struct {
	grpc.ClientStream
}

func (x *apiGetClientsClient) Recv() (*Client, error) {
	m := new(Client)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *apiClient) RunBackup(ctx context.Context, in *RunBackupParams, opts ...grpc.CallOption) (*Error, error) {
	out := new(Error)
	err := c.cc.Invoke(ctx, "/api.Api/RunBackup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) RunRestore(ctx context.Context, in *RunRestoreParams, opts ...grpc.CallOption) (*RunRestoreResponse, error) {
	out := new(RunRestoreResponse)
	err := c.cc.Invoke(ctx, "/api.Api/RunRestore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) LastBackupMetadata(ctx context.Context, in *LastBackupMetadataParams, opts ...grpc.CallOption) (*BackupMetadata, error) {
	out := new(BackupMetadata)
	err := c.cc.Invoke(ctx, "/api.Api/LastBackupMetadata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) BackupsMetadata(ctx context.Context, in *BackupsMetadataParams, opts ...grpc.CallOption) (Api_BackupsMetadataClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Api_serviceDesc.Streams[1], "/api.Api/BackupsMetadata", opts...)
	if err != nil {
		return nil, err
	}
	x := &apiBackupsMetadataClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Api_BackupsMetadataClient interface {
	Recv() (*MetadataFile, error)
	grpc.ClientStream
}

type apiBackupsMetadataClient struct {
	grpc.ClientStream
}

func (x *apiBackupsMetadataClient) Recv() (*MetadataFile, error) {
	m := new(MetadataFile)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ApiServer is the server API for Api service.
type ApiServer interface {
	GetClients(*Empty, Api_GetClientsServer) error
	RunBackup(context.Context, *RunBackupParams) (*Error, error)
	RunRestore(context.Context, *RunRestoreParams) (*RunRestoreResponse, error)
	LastBackupMetadata(context.Context, *LastBackupMetadataParams) (*BackupMetadata, error)
	BackupsMetadata(*BackupsMetadataParams, Api_BackupsMetadataServer) error
}

func RegisterApiServer(s *grpc.Server, srv ApiServer) {
	s.RegisterService(&_Api_serviceDesc, srv)
}

func _Api_GetClients_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApiServer).GetClients(m, &apiGetClientsServer{stream})
}

type Api_GetClientsServer interface {
	Send(*Client) error
	grpc.ServerStream
}

type apiGetClientsServer struct {
	grpc.ServerStream
}

func (x *apiGetClientsServer) Send(m *Client) error {
	return x.ServerStream.SendMsg(m)
}

func _Api_RunBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunBackupParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).RunBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/RunBackup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).RunBackup(ctx, req.(*RunBackupParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_RunRestore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRestoreParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).RunRestore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/RunRestore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).RunRestore(ctx, req.(*RunRestoreParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_LastBackupMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LastBackupMetadataParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).LastBackupMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/LastBackupMetadata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).LastBackupMetadata(ctx, req.(*LastBackupMetadataParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_BackupsMetadata_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BackupsMetadataParams)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApiServer).BackupsMetadata(m, &apiBackupsMetadataServer{stream})
}

type Api_BackupsMetadataServer interface {
	Send(*MetadataFile) error
	grpc.ServerStream
}

type apiBackupsMetadataServer struct {
	grpc.ServerStream
}

func (x *apiBackupsMetadataServer) Send(m *MetadataFile) error {
	return x.ServerStream.SendMsg(m)
}

var _Api_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Api",
	HandlerType: (*ApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunBackup",
			Handler:    _Api_RunBackup_Handler,
		},
		{
			MethodName: "RunRestore",
			Handler:    _Api_RunRestore_Handler,
		},
		{
			MethodName: "LastBackupMetadata",
			Handler:    _Api_LastBackupMetadata_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetClients",
			Handler:       _Api_GetClients_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "BackupsMetadata",
			Handler:       _Api_BackupsMetadata_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/api.proto",
}
